// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/jdk/internal/classfile/ClassTransform.h>

#ifndef SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM_FWD
#define SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::jdk::internal::classfile::impl { class TransformImpl_UnresolvedClassTransform; }

template<>
struct scapix::jni::object_traits<scapix::java_api::jdk::internal::classfile::impl::TransformImpl_UnresolvedClassTransform>
{
	static constexpr fixed_string class_name = "jdk/internal/classfile/impl/TransformImpl$UnresolvedClassTransform";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::jdk::internal::classfile::ClassTransform>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM)
#define SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/jdk/internal/classfile/ClassBuilder.h>
#include <scapix/java_api/jdk/internal/classfile/ClassElement.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class jdk::internal::classfile::impl::TransformImpl_UnresolvedClassTransform : public jni::object_base<"jdk/internal/classfile/impl/TransformImpl$UnresolvedClassTransform",
	java::lang::Object,
	jdk::internal::classfile::ClassTransform>
{
public:

	void accept(jni::ref<jdk::internal::classfile::ClassBuilder> builder, jni::ref<jdk::internal::classfile::ClassElement> element) { return call_method<"accept", void>(builder, element); }
	void atEnd(jni::ref<jdk::internal::classfile::ClassBuilder> builder) { return call_method<"atEnd", void>(builder); }
	void atStart(jni::ref<jdk::internal::classfile::ClassBuilder> builder) { return call_method<"atStart", void>(builder); }

protected:

	TransformImpl_UnresolvedClassTransform(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_IMPL_TRANSFORMIMPL_UNRESOLVEDCLASSTRANSFORM
