// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER_FWD
#define SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::org::apache::xerces::internal::impl::xs::models { class CMBuilder; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::org::apache::xerces::internal::impl::xs::models::CMBuilder>
{
	static constexpr fixed_string class_name = "com/sun/org/apache/xerces/internal/impl/xs/models/CMBuilder";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER)
#define SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/com/sun/org/apache/xerces/internal/impl/xs/XSComplexTypeDecl.h>
#include <scapix/java_api/com/sun/org/apache/xerces/internal/impl/xs/XSDeclarationPool.h>
#include <scapix/java_api/com/sun/org/apache/xerces/internal/impl/xs/models/CMNodeFactory.h>
#include <scapix/java_api/com/sun/org/apache/xerces/internal/impl/xs/models/XSCMValidator.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::org::apache::xerces::internal::impl::xs::models::CMBuilder : public jni::object_base<"com/sun/org/apache/xerces/internal/impl/xs/models/CMBuilder",
	java::lang::Object>
{
public:

	static jni::ref<com::sun::org::apache::xerces::internal::impl::xs::models::CMBuilder> new_object(jni::ref<com::sun::org::apache::xerces::internal::impl::xs::models::CMNodeFactory> p1) { return base_::new_object(p1); }
	void setDeclPool(jni::ref<com::sun::org::apache::xerces::internal::impl::xs::XSDeclarationPool> p1) { return call_method<"setDeclPool", void>(p1); }
	jni::ref<com::sun::org::apache::xerces::internal::impl::xs::models::XSCMValidator> getContentModel(jni::ref<com::sun::org::apache::xerces::internal::impl::xs::XSComplexTypeDecl> p1, jboolean p2) { return call_method<"getContentModel", jni::ref<com::sun::org::apache::xerces::internal::impl::xs::models::XSCMValidator>>(p1, p2); }

protected:

	CMBuilder(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XERCES_INTERNAL_IMPL_XS_MODELS_CMBUILDER
