// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK_FWD
#define SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::view::displayhash { class DisplayHashResultCallback; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::view::displayhash::DisplayHashResultCallback>
{
	static constexpr fixed_string class_name = "android/view/displayhash/DisplayHashResultCallback";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK)
#define SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/view/displayhash/DisplayHash.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::view::displayhash::DisplayHashResultCallback : public jni::object_base<"android/view/displayhash/DisplayHashResultCallback",
	java::lang::Object>
{
public:

	static jint DISPLAY_HASH_ERROR_INVALID_BOUNDS() { return get_static_field<"DISPLAY_HASH_ERROR_INVALID_BOUNDS", jint>(); }
	static jint DISPLAY_HASH_ERROR_INVALID_HASH_ALGORITHM() { return get_static_field<"DISPLAY_HASH_ERROR_INVALID_HASH_ALGORITHM", jint>(); }
	static jint DISPLAY_HASH_ERROR_MISSING_WINDOW() { return get_static_field<"DISPLAY_HASH_ERROR_MISSING_WINDOW", jint>(); }
	static jint DISPLAY_HASH_ERROR_NOT_VISIBLE_ON_SCREEN() { return get_static_field<"DISPLAY_HASH_ERROR_NOT_VISIBLE_ON_SCREEN", jint>(); }
	static jint DISPLAY_HASH_ERROR_TOO_MANY_REQUESTS() { return get_static_field<"DISPLAY_HASH_ERROR_TOO_MANY_REQUESTS", jint>(); }
	static jint DISPLAY_HASH_ERROR_UNKNOWN() { return get_static_field<"DISPLAY_HASH_ERROR_UNKNOWN", jint>(); }

	void onDisplayHashResult(jni::ref<android::view::displayhash::DisplayHash> p1) { return call_method<"onDisplayHashResult", void>(p1); }
	void onDisplayHashError(jint p1) { return call_method<"onDisplayHashError", void>(p1); }

protected:

	DisplayHashResultCallback(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_DISPLAYHASH_DISPLAYHASHRESULTCALLBACK
