// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/jdk/incubator/vector/VectorOperators_Operator.h>

#ifndef SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY_FWD
#define SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace jdk::incubator::vector {

class VectorOperators_Unary;

} // namespace jdk::incubator::vector
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::jdk::incubator::vector::VectorOperators_Unary>
{
	static constexpr fixed_string class_name = "jdk/incubator/vector/VectorOperators$Unary";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::jdk::incubator::vector::VectorOperators_Operator>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY
#define SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class jdk::incubator::vector::VectorOperators_Unary : public jni::object_base<"jdk/incubator/vector/VectorOperators$Unary",
	java::lang::Object,
	jdk::incubator::vector::VectorOperators_Operator>
{
public:
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INCUBATOR_VECTOR_VECTOROPERATORS_UNARY
#endif // SCAPIX_JAVA_API_FWD
