// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/io/InputStream.h>

#ifndef SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM_FWD
#define SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::content::res { class AssetManager_AssetInputStream; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::content::res::AssetManager_AssetInputStream>
{
	static constexpr fixed_string class_name = "android/content/res/AssetManager$AssetInputStream";
	using base_classes = std::tuple<scapix::java_api::java::io::InputStream>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM)
#define SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::content::res::AssetManager_AssetInputStream : public jni::object_base<"android/content/res/AssetManager$AssetInputStream",
	java::io::InputStream>
{
public:

	jint read() { return call_method<"read", jint>(); }
	jboolean markSupported() { return call_method<"markSupported", jboolean>(); }
	jint available() { return call_method<"available", jint>(); }
	void close() { return call_method<"close", void>(); }
	void mark(jint readlimit) { return call_method<"mark", void>(readlimit); }
	void reset() { return call_method<"reset", void>(); }
	jint read(jni::ref<jni::array<jbyte>> b) { return call_method<"read", jint>(b); }
	jint read(jni::ref<jni::array<jbyte>> b, jint off, jint len) { return call_method<"read", jint>(b, off, len); }
	jlong skip(jlong n) { return call_method<"skip", jlong>(n); }

protected:

	AssetManager_AssetInputStream(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_CONTENT_RES_ASSETMANAGER_ASSETINPUTSTREAM
