// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/sun/security/provider/DigestBase.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::security::provider { class SHA5; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::provider::SHA5>
{
	static constexpr fixed_string class_name = "sun/security/provider/SHA5";
	using base_classes = std::tuple<scapix::java_api::sun::security::provider::DigestBase>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5)
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/sun/security/provider/SHA5_SHA512.h>
#include <scapix/java_api/sun/security/provider/SHA5_SHA384.h>
#include <scapix/java_api/sun/security/provider/SHA5_SHA512_224.h>
#include <scapix/java_api/sun/security/provider/SHA5_SHA512_256.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class sun::security::provider::SHA5 : public jni::object_base<"sun/security/provider/SHA5",
	sun::security::provider::DigestBase>
{
public:

	using SHA512 = SHA5_SHA512;
	using SHA384 = SHA5_SHA384;
	using SHA512_224 = SHA5_SHA512_224;
	using SHA512_256 = SHA5_SHA512_256;

	jni::ref<java::lang::Object> clone() { return call_method<"clone", jni::ref<java::lang::Object>>(); }

protected:

	SHA5(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_SHA5
