// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER_FWD
#define SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::naming { class NameParser; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::naming::NameParser>
{
	static constexpr fixed_string class_name = "javax/naming/NameParser";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER)
#define SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/javax/naming/Name.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::naming::NameParser : public jni::object_base<"javax/naming/NameParser",
	java::lang::Object>
{
public:

	jni::ref<javax::naming::Name> parse(jni::ref<java::lang::String> p1) { return call_method<"parse", jni::ref<javax::naming::Name>>(p1); }

protected:

	NameParser(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_NAMING_NAMEPARSER
