// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS_FWD
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::provider { class CalendarContract_AttendeesColumns; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::provider::CalendarContract_AttendeesColumns>
{
	static constexpr fixed_string class_name = "android/provider/CalendarContract$AttendeesColumns";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS)
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::provider::CalendarContract_AttendeesColumns : public jni::object_base<"android/provider/CalendarContract$AttendeesColumns",
	java::lang::Object>
{
public:

	static jni::ref<java::lang::String> ATTENDEE_EMAIL() { return get_static_field<"ATTENDEE_EMAIL", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> ATTENDEE_IDENTITY() { return get_static_field<"ATTENDEE_IDENTITY", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> ATTENDEE_ID_NAMESPACE() { return get_static_field<"ATTENDEE_ID_NAMESPACE", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> ATTENDEE_NAME() { return get_static_field<"ATTENDEE_NAME", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> ATTENDEE_RELATIONSHIP() { return get_static_field<"ATTENDEE_RELATIONSHIP", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> ATTENDEE_STATUS() { return get_static_field<"ATTENDEE_STATUS", jni::ref<java::lang::String>>(); }
	static jint ATTENDEE_STATUS_ACCEPTED() { return get_static_field<"ATTENDEE_STATUS_ACCEPTED", jint>(); }
	static jint ATTENDEE_STATUS_DECLINED() { return get_static_field<"ATTENDEE_STATUS_DECLINED", jint>(); }
	static jint ATTENDEE_STATUS_INVITED() { return get_static_field<"ATTENDEE_STATUS_INVITED", jint>(); }
	static jint ATTENDEE_STATUS_NONE() { return get_static_field<"ATTENDEE_STATUS_NONE", jint>(); }
	static jint ATTENDEE_STATUS_TENTATIVE() { return get_static_field<"ATTENDEE_STATUS_TENTATIVE", jint>(); }
	static jni::ref<java::lang::String> ATTENDEE_TYPE() { return get_static_field<"ATTENDEE_TYPE", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> EVENT_ID() { return get_static_field<"EVENT_ID", jni::ref<java::lang::String>>(); }
	static jint RELATIONSHIP_ATTENDEE() { return get_static_field<"RELATIONSHIP_ATTENDEE", jint>(); }
	static jint RELATIONSHIP_NONE() { return get_static_field<"RELATIONSHIP_NONE", jint>(); }
	static jint RELATIONSHIP_ORGANIZER() { return get_static_field<"RELATIONSHIP_ORGANIZER", jint>(); }
	static jint RELATIONSHIP_PERFORMER() { return get_static_field<"RELATIONSHIP_PERFORMER", jint>(); }
	static jint RELATIONSHIP_SPEAKER() { return get_static_field<"RELATIONSHIP_SPEAKER", jint>(); }
	static jint TYPE_NONE() { return get_static_field<"TYPE_NONE", jint>(); }
	static jint TYPE_OPTIONAL() { return get_static_field<"TYPE_OPTIONAL", jint>(); }
	static jint TYPE_REQUIRED() { return get_static_field<"TYPE_REQUIRED", jint>(); }
	static jint TYPE_RESOURCE() { return get_static_field<"TYPE_RESOURCE", jint>(); }


protected:

	CalendarContract_AttendeesColumns(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_CALENDARCONTRACT_ATTENDEESCOLUMNS
