// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/jdk/internal/classfile/Attribute.h>
#include <scapix/java_api/jdk/internal/classfile/ClassElement.h>

#ifndef SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE_FWD
#define SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::jdk::internal::classfile::attribute { class ModuleTargetAttribute; }

template<>
struct scapix::jni::object_traits<scapix::java_api::jdk::internal::classfile::attribute::ModuleTargetAttribute>
{
	static constexpr fixed_string class_name = "jdk/internal/classfile/attribute/ModuleTargetAttribute";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::jdk::internal::classfile::Attribute, scapix::java_api::jdk::internal::classfile::ClassElement>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE)
#define SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/jdk/internal/classfile/constantpool/Utf8Entry.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class jdk::internal::classfile::attribute::ModuleTargetAttribute : public jni::object_base<"jdk/internal/classfile/attribute/ModuleTargetAttribute",
	java::lang::Object,
	jdk::internal::classfile::Attribute,
	jdk::internal::classfile::ClassElement>
{
public:

	jni::ref<jdk::internal::classfile::constantpool::Utf8Entry> targetPlatform() { return call_method<"targetPlatform", jni::ref<jdk::internal::classfile::constantpool::Utf8Entry>>(); }
	static jni::ref<jdk::internal::classfile::attribute::ModuleTargetAttribute> of(jni::ref<java::lang::String> targetPlatform) { return call_static_method<"of", jni::ref<jdk::internal::classfile::attribute::ModuleTargetAttribute>>(targetPlatform); }
	static jni::ref<jdk::internal::classfile::attribute::ModuleTargetAttribute> of(jni::ref<jdk::internal::classfile::constantpool::Utf8Entry> targetPlatform) { return call_static_method<"of", jni::ref<jdk::internal::classfile::attribute::ModuleTargetAttribute>>(targetPlatform); }

protected:

	ModuleTargetAttribute(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_CLASSFILE_ATTRIBUTE_MODULETARGETATTRIBUTE
