// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK_FWD
#define SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::telecom { class Call_Callback; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::telecom::Call_Callback>
{
	static constexpr fixed_string class_name = "android/telecom/Call$Callback";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK)
#define SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/os/Bundle.h>
#include <scapix/java_api/android/telecom/Call.h>
#include <scapix/java_api/android/telecom/Call_Details.h>
#include <scapix/java_api/android/telecom/InCallService_VideoCall.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/List.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::telecom::Call_Callback : public jni::object_base<"android/telecom/Call$Callback",
	java::lang::Object>
{
public:

	static jni::ref<android::telecom::Call_Callback> new_object() { return base_::new_object(); }
	void onStateChanged(jni::ref<android::telecom::Call> call, jint state) { return call_method<"onStateChanged", void>(call, state); }
	void onParentChanged(jni::ref<android::telecom::Call> call, jni::ref<android::telecom::Call> parent) { return call_method<"onParentChanged", void>(call, parent); }
	void onChildrenChanged(jni::ref<android::telecom::Call> call, jni::ref<java::util::List> children) { return call_method<"onChildrenChanged", void>(call, children); }
	void onDetailsChanged(jni::ref<android::telecom::Call> call, jni::ref<android::telecom::Call_Details> details) { return call_method<"onDetailsChanged", void>(call, details); }
	void onCannedTextResponsesLoaded(jni::ref<android::telecom::Call> call, jni::ref<java::util::List> cannedTextResponses) { return call_method<"onCannedTextResponsesLoaded", void>(call, cannedTextResponses); }
	void onPostDialWait(jni::ref<android::telecom::Call> call, jni::ref<java::lang::String> remainingPostDialSequence) { return call_method<"onPostDialWait", void>(call, remainingPostDialSequence); }
	void onVideoCallChanged(jni::ref<android::telecom::Call> call, jni::ref<android::telecom::InCallService_VideoCall> videoCall) { return call_method<"onVideoCallChanged", void>(call, videoCall); }
	void onCallDestroyed(jni::ref<android::telecom::Call> call) { return call_method<"onCallDestroyed", void>(call); }
	void onConferenceableCallsChanged(jni::ref<android::telecom::Call> call, jni::ref<java::util::List> conferenceableCalls) { return call_method<"onConferenceableCallsChanged", void>(call, conferenceableCalls); }
	void onConnectionEvent(jni::ref<android::telecom::Call> call, jni::ref<java::lang::String> event, jni::ref<android::os::Bundle> extras) { return call_method<"onConnectionEvent", void>(call, event, extras); }

protected:

	Call_Callback(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_TELECOM_CALL_CALLBACK
