// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/provider/BaseColumns.h>
#include <scapix/java_api/android/provider/Contacts_PhonesColumns.h>
#include <scapix/java_api/android/provider/Contacts_PeopleColumns.h>

#ifndef SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES_FWD
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::provider { class Contacts_People_Phones; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::provider::Contacts_People_Phones>
{
	static constexpr fixed_string class_name = "android/provider/Contacts$People$Phones";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::android::provider::BaseColumns, scapix::java_api::android::provider::Contacts_PhonesColumns, scapix::java_api::android::provider::Contacts_PeopleColumns>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES)
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::provider::Contacts_People_Phones : public jni::object_base<"android/provider/Contacts$People$Phones",
	java::lang::Object,
	android::provider::BaseColumns,
	android::provider::Contacts_PhonesColumns,
	android::provider::Contacts_PeopleColumns>
{
public:

	static jni::ref<java::lang::String> CONTENT_DIRECTORY() { return get_static_field<"CONTENT_DIRECTORY", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> DEFAULT_SORT_ORDER() { return get_static_field<"DEFAULT_SORT_ORDER", jni::ref<java::lang::String>>(); }


protected:

	Contacts_People_Phones(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_CONTACTS_PEOPLE_PHONES
