// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/android/util/AndroidRuntimeException.h>

#ifndef SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION_FWD
#define SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace android::app {

class InfeasibleActivityOptionsException;

} // namespace android::app
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::android::app::InfeasibleActivityOptionsException>
{
	static constexpr fixed_string class_name = "android/app/InfeasibleActivityOptionsException";
	using base_classes = std::tuple<scapix::java_api::android::util::AndroidRuntimeException>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION
#define SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::app::InfeasibleActivityOptionsException : public jni::object_base<"android/app/InfeasibleActivityOptionsException",
	android::util::AndroidRuntimeException>
{
public:
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_APP_INFEASIBLEACTIVITYOPTIONSEXCEPTION
#endif // SCAPIX_JAVA_API_FWD
