// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/javax/swing/JLabel.h>
#include <scapix/java_api/javax/swing/table/TableCellRenderer.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace javax::swing::table {

class DefaultTableCellRenderer;

} // namespace javax::swing::table
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::table::DefaultTableCellRenderer>
{
	static constexpr fixed_string class_name = "javax/swing/table/DefaultTableCellRenderer";
	using base_classes = std::tuple<scapix::java_api::javax::swing::JLabel, scapix::java_api::javax::swing::table::TableCellRenderer, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER
#define SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/awt/Color.h>
#include <scapix/java_api/java/awt/Component.h>
#include <scapix/java_api/java/awt/Rectangle.h>
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/javax/swing/JTable.h>
#include <scapix/java_api/javax/swing/table/DefaultTableCellRenderer_UIResource.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::swing::table::DefaultTableCellRenderer : public jni::object_base<"javax/swing/table/DefaultTableCellRenderer",
	javax::swing::JLabel,
	javax::swing::table::TableCellRenderer,
	java::io::Serializable>
{
public:

	using UIResource = DefaultTableCellRenderer_UIResource;

	static jni::ref<javax::swing::table::DefaultTableCellRenderer> new_object() { return object_base::new_object(); }
	void setForeground(jni::ref<java::awt::Color> c) { return call_method<"setForeground", void>(c); }
	void setBackground(jni::ref<java::awt::Color> c) { return call_method<"setBackground", void>(c); }
	void updateUI() { return call_method<"updateUI", void>(); }
	jni::ref<java::awt::Component> getTableCellRendererComponent(jni::ref<javax::swing::JTable> table, jni::ref<java::lang::Object> value, jboolean isSelected, jboolean hasFocus, jint row, jint column) { return call_method<"getTableCellRendererComponent", jni::ref<java::awt::Component>>(table, value, isSelected, hasFocus, row, column); }
	jboolean isOpaque() { return call_method<"isOpaque", jboolean>(); }
	void invalidate() { return call_method<"invalidate", void>(); }
	void validate() { return call_method<"validate", void>(); }
	void revalidate() { return call_method<"revalidate", void>(); }
	void repaint(jlong tm, jint x, jint y, jint width, jint height) { return call_method<"repaint", void>(tm, x, y, width, height); }
	void repaint(jni::ref<java::awt::Rectangle> r) { return call_method<"repaint", void>(r); }
	void repaint() { return call_method<"repaint", void>(); }
	void firePropertyChange(jni::ref<java::lang::String> propertyName, jboolean oldValue, jboolean newValue) { return call_method<"firePropertyChange", void>(propertyName, oldValue, newValue); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TABLE_DEFAULTTABLECELLRENDERER
#endif // SCAPIX_JAVA_API_FWD
