// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/time/temporal/Temporal.h>
#include <scapix/java_api/java/time/temporal/TemporalAdjuster.h>
#include <scapix/java_api/java/lang/Comparable.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME_FWD
#define SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::time { class OffsetTime; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::time::OffsetTime>
{
	static constexpr fixed_string class_name = "java/time/OffsetTime";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::java::time::temporal::Temporal, scapix::java_api::java::time::temporal::TemporalAdjuster, scapix::java_api::java::lang::Comparable, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME)
#define SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/CharSequence.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/time/Clock.h>
#include <scapix/java_api/java/time/Instant.h>
#include <scapix/java_api/java/time/LocalDate.h>
#include <scapix/java_api/java/time/LocalTime.h>
#include <scapix/java_api/java/time/OffsetDateTime.h>
#include <scapix/java_api/java/time/ZoneId.h>
#include <scapix/java_api/java/time/ZoneOffset.h>
#include <scapix/java_api/java/time/format/DateTimeFormatter.h>
#include <scapix/java_api/java/time/temporal/TemporalAccessor.h>
#include <scapix/java_api/java/time/temporal/TemporalAmount.h>
#include <scapix/java_api/java/time/temporal/TemporalField.h>
#include <scapix/java_api/java/time/temporal/TemporalQuery.h>
#include <scapix/java_api/java/time/temporal/TemporalUnit.h>
#include <scapix/java_api/java/time/temporal/ValueRange.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::time::OffsetTime : public jni::object_base<"java/time/OffsetTime",
	java::lang::Object,
	java::time::temporal::Temporal,
	java::time::temporal::TemporalAdjuster,
	java::lang::Comparable,
	java::io::Serializable>
{
public:

	static jni::ref<java::time::OffsetTime> MIN() { return get_static_field<"MIN", jni::ref<java::time::OffsetTime>>(); }
	static jni::ref<java::time::OffsetTime> MAX() { return get_static_field<"MAX", jni::ref<java::time::OffsetTime>>(); }

	static jni::ref<java::time::OffsetTime> now() { return call_static_method<"now", jni::ref<java::time::OffsetTime>>(); }
	static jni::ref<java::time::OffsetTime> now(jni::ref<java::time::ZoneId> p1) { return call_static_method<"now", jni::ref<java::time::OffsetTime>>(p1); }
	static jni::ref<java::time::OffsetTime> now(jni::ref<java::time::Clock> p1) { return call_static_method<"now", jni::ref<java::time::OffsetTime>>(p1); }
	static jni::ref<java::time::OffsetTime> of(jni::ref<java::time::LocalTime> p1, jni::ref<java::time::ZoneOffset> p2) { return call_static_method<"of", jni::ref<java::time::OffsetTime>>(p1, p2); }
	static jni::ref<java::time::OffsetTime> of(jint p1, jint p2, jint p3, jint p4, jni::ref<java::time::ZoneOffset> p5) { return call_static_method<"of", jni::ref<java::time::OffsetTime>>(p1, p2, p3, p4, p5); }
	static jni::ref<java::time::OffsetTime> ofInstant(jni::ref<java::time::Instant> p1, jni::ref<java::time::ZoneId> p2) { return call_static_method<"ofInstant", jni::ref<java::time::OffsetTime>>(p1, p2); }
	static jni::ref<java::time::OffsetTime> from(jni::ref<java::time::temporal::TemporalAccessor> p1) { return call_static_method<"from", jni::ref<java::time::OffsetTime>>(p1); }
	static jni::ref<java::time::OffsetTime> parse(jni::ref<java::lang::CharSequence> p1) { return call_static_method<"parse", jni::ref<java::time::OffsetTime>>(p1); }
	static jni::ref<java::time::OffsetTime> parse(jni::ref<java::lang::CharSequence> p1, jni::ref<java::time::format::DateTimeFormatter> p2) { return call_static_method<"parse", jni::ref<java::time::OffsetTime>>(p1, p2); }
	jboolean isSupported(jni::ref<java::time::temporal::TemporalField> p1) { return call_method<"isSupported", jboolean>(p1); }
	jboolean isSupported(jni::ref<java::time::temporal::TemporalUnit> p1) { return call_method<"isSupported", jboolean>(p1); }
	jni::ref<java::time::temporal::ValueRange> range(jni::ref<java::time::temporal::TemporalField> p1) { return call_method<"range", jni::ref<java::time::temporal::ValueRange>>(p1); }
	jint get(jni::ref<java::time::temporal::TemporalField> p1) { return call_method<"get", jint>(p1); }
	jlong getLong(jni::ref<java::time::temporal::TemporalField> p1) { return call_method<"getLong", jlong>(p1); }
	jni::ref<java::time::ZoneOffset> getOffset() { return call_method<"getOffset", jni::ref<java::time::ZoneOffset>>(); }
	jni::ref<java::time::OffsetTime> withOffsetSameLocal(jni::ref<java::time::ZoneOffset> p1) { return call_method<"withOffsetSameLocal", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> withOffsetSameInstant(jni::ref<java::time::ZoneOffset> p1) { return call_method<"withOffsetSameInstant", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::LocalTime> toLocalTime() { return call_method<"toLocalTime", jni::ref<java::time::LocalTime>>(); }
	jint getHour() { return call_method<"getHour", jint>(); }
	jint getMinute() { return call_method<"getMinute", jint>(); }
	jint getSecond() { return call_method<"getSecond", jint>(); }
	jint getNano() { return call_method<"getNano", jint>(); }
	jni::ref<java::time::OffsetTime> with(jni::ref<java::time::temporal::TemporalAdjuster> p1) { return call_method<"with", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> with(jni::ref<java::time::temporal::TemporalField> p1, jlong p2) { return call_method<"with", jni::ref<java::time::OffsetTime>>(p1, p2); }
	jni::ref<java::time::OffsetTime> withHour(jint p1) { return call_method<"withHour", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> withMinute(jint p1) { return call_method<"withMinute", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> withSecond(jint p1) { return call_method<"withSecond", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> withNano(jint p1) { return call_method<"withNano", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> truncatedTo(jni::ref<java::time::temporal::TemporalUnit> p1) { return call_method<"truncatedTo", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> plus(jni::ref<java::time::temporal::TemporalAmount> p1) { return call_method<"plus", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> plus(jlong p1, jni::ref<java::time::temporal::TemporalUnit> p2) { return call_method<"plus", jni::ref<java::time::OffsetTime>>(p1, p2); }
	jni::ref<java::time::OffsetTime> plusHours(jlong p1) { return call_method<"plusHours", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> plusMinutes(jlong p1) { return call_method<"plusMinutes", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> plusSeconds(jlong p1) { return call_method<"plusSeconds", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> plusNanos(jlong p1) { return call_method<"plusNanos", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> minus(jni::ref<java::time::temporal::TemporalAmount> p1) { return call_method<"minus", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> minus(jlong p1, jni::ref<java::time::temporal::TemporalUnit> p2) { return call_method<"minus", jni::ref<java::time::OffsetTime>>(p1, p2); }
	jni::ref<java::time::OffsetTime> minusHours(jlong p1) { return call_method<"minusHours", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> minusMinutes(jlong p1) { return call_method<"minusMinutes", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> minusSeconds(jlong p1) { return call_method<"minusSeconds", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::time::OffsetTime> minusNanos(jlong p1) { return call_method<"minusNanos", jni::ref<java::time::OffsetTime>>(p1); }
	jni::ref<java::lang::Object> query(jni::ref<java::time::temporal::TemporalQuery> p1) { return call_method<"query", jni::ref<java::lang::Object>>(p1); }
	jni::ref<java::time::temporal::Temporal> adjustInto(jni::ref<java::time::temporal::Temporal> p1) { return call_method<"adjustInto", jni::ref<java::time::temporal::Temporal>>(p1); }
	jlong until(jni::ref<java::time::temporal::Temporal> p1, jni::ref<java::time::temporal::TemporalUnit> p2) { return call_method<"until", jlong>(p1, p2); }
	jni::ref<java::lang::String> format(jni::ref<java::time::format::DateTimeFormatter> p1) { return call_method<"format", jni::ref<java::lang::String>>(p1); }
	jni::ref<java::time::OffsetDateTime> atDate(jni::ref<java::time::LocalDate> p1) { return call_method<"atDate", jni::ref<java::time::OffsetDateTime>>(p1); }
	jint compareTo(jni::ref<java::time::OffsetTime> p1) { return call_method<"compareTo", jint>(p1); }
	jboolean isAfter(jni::ref<java::time::OffsetTime> p1) { return call_method<"isAfter", jboolean>(p1); }
	jboolean isBefore(jni::ref<java::time::OffsetTime> p1) { return call_method<"isBefore", jboolean>(p1); }
	jboolean isEqual(jni::ref<java::time::OffsetTime> p1) { return call_method<"isEqual", jboolean>(p1); }
	jboolean equals(jni::ref<java::lang::Object> p1) { return call_method<"equals", jboolean>(p1); }
	jint hashCode() { return call_method<"hashCode", jint>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }

protected:

	OffsetTime(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_TIME_OFFSETTIME
