// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/util/function/Function.h>

#ifndef SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR_FWD
#define SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::util::function { class UnaryOperator; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::util::function::UnaryOperator>
{
	static constexpr fixed_string class_name = "java/util/function/UnaryOperator";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::java::util::function::Function>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR)
#define SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::util::function::UnaryOperator : public jni::object_base<"java/util/function/UnaryOperator",
	java::lang::Object,
	java::util::function::Function>
{
public:

	static jni::ref<java::util::function::UnaryOperator> identity() { return call_static_method<"identity", jni::ref<java::util::function::UnaryOperator>>(); }

protected:

	UnaryOperator(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_UTIL_FUNCTION_UNARYOPERATOR
