// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER_FWD
#define SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace android::adservices::adselection {

class SetAppInstallAdvertisersRequest_Builder;

} // namespace android::adservices::adselection
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::android::adservices::adselection::SetAppInstallAdvertisersRequest_Builder>
{
	static constexpr fixed_string class_name = "android/adservices/adselection/SetAppInstallAdvertisersRequest$Builder";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER
#define SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/adservices/adselection/SetAppInstallAdvertisersRequest.h>
#include <scapix/java_api/java/util/Set.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::adservices::adselection::SetAppInstallAdvertisersRequest_Builder : public jni::object_base<"android/adservices/adselection/SetAppInstallAdvertisersRequest$Builder",
	java::lang::Object>
{
public:

	static jni::ref<android::adservices::adselection::SetAppInstallAdvertisersRequest_Builder> new_object() { return object_base::new_object(); }
	jni::ref<android::adservices::adselection::SetAppInstallAdvertisersRequest> build() { return call_method<"build", jni::ref<android::adservices::adselection::SetAppInstallAdvertisersRequest>>(); }
	jni::ref<android::adservices::adselection::SetAppInstallAdvertisersRequest_Builder> setAdvertisers(jni::ref<java::util::Set> advertisers) { return call_method<"setAdvertisers", jni::ref<android::adservices::adselection::SetAppInstallAdvertisersRequest_Builder>>(advertisers); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_ADSERVICES_ADSELECTION_SETAPPINSTALLADVERTISERSREQUEST_BUILDER
#endif // SCAPIX_JAVA_API_FWD
