// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN_FWD
#define SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::management::snmp::jvmmib { class JvmRTLibraryPathEntryMBean; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::management::snmp::jvmmib::JvmRTLibraryPathEntryMBean>
{
	static constexpr fixed_string class_name = "sun/management/snmp/jvmmib/JvmRTLibraryPathEntryMBean";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN)
#define SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Integer.h>
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::management::snmp::jvmmib::JvmRTLibraryPathEntryMBean : public jni::object_base<"sun/management/snmp/jvmmib/JvmRTLibraryPathEntryMBean",
	java::lang::Object>
{
public:

	jni::ref<java::lang::String> getJvmRTLibraryPathItem() { return call_method<"getJvmRTLibraryPathItem", jni::ref<java::lang::String>>(); }
	jni::ref<java::lang::Integer> getJvmRTLibraryPathIndex() { return call_method<"getJvmRTLibraryPathIndex", jni::ref<java::lang::Integer>>(); }

protected:

	JvmRTLibraryPathEntryMBean(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_MANAGEMENT_SNMP_JVMMIB_JVMRTLIBRARYPATHENTRYMBEAN
