// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER_FWD
#define SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::xml::stream { class XMLReporter; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::xml::stream::XMLReporter>
{
	static constexpr fixed_string class_name = "javax/xml/stream/XMLReporter";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER)
#define SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/javax/xml/stream/Location.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::xml::stream::XMLReporter : public jni::object_base<"javax/xml/stream/XMLReporter",
	java::lang::Object>
{
public:

	void report(jni::ref<java::lang::String> p1, jni::ref<java::lang::String> p2, jni::ref<java::lang::Object> p3, jni::ref<javax::xml::stream::Location> p4) { return call_method<"report", void>(p1, p2, p3, p4); }

protected:

	XMLReporter(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_XML_STREAM_XMLREPORTER
