// Generated by Scapix Java API 2.1
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api { namespace sun::security::validator { class ChunghwaTLSPolicy; }}

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::validator::ChunghwaTLSPolicy>
{
	static constexpr fixed_string class_name = "sun/security/validator/ChunghwaTLSPolicy";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY)
#define SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class sun::security::validator::ChunghwaTLSPolicy : public jni::object_base<"sun/security/validator/ChunghwaTLSPolicy",
	java::lang::Object>
{
public:


};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_VALIDATOR_CHUNGHWATLSPOLICY
