// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/com/sun/org/apache/xml/internal/dtm/ref/DTMManagerDefault.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER_FWD
#define SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::org::apache::xalan::internal::xsltc::dom { class XSLTCDTMManager; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager>
{
	static constexpr fixed_string class_name = "com/sun/org/apache/xalan/internal/xsltc/dom/XSLTCDTMManager";
	using base_classes = std::tuple<scapix::java_api::com::sun::org::apache::xml::internal::dtm::ref::DTMManagerDefault>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER)
#define SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/com/sun/org/apache/xml/internal/dtm/DTM.h>
#include <scapix/java_api/com/sun/org/apache/xml/internal/dtm/DTMWSFilter.h>
#include <scapix/java_api/javax/xml/transform/Source.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager : public jni::object_base<"com/sun/org/apache/xalan/internal/xsltc/dom/XSLTCDTMManager",
	com::sun::org::apache::xml::internal::dtm::ref::DTMManagerDefault>
{
public:

	static jni::ref<com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager> new_object() { return base_::new_object(); }
	static jni::ref<com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager> newInstance() { return call_static_method<"newInstance", jni::ref<com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager>>(); }
	static jni::ref<com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager> createNewDTMManagerInstance() { return call_static_method<"createNewDTMManagerInstance", jni::ref<com::sun::org::apache::xalan::internal::xsltc::dom::XSLTCDTMManager>>(); }
	jni::ref<com::sun::org::apache::xml::internal::dtm::DTM> getDTM(jni::ref<javax::xml::transform::Source> p1, jboolean p2, jni::ref<com::sun::org::apache::xml::internal::dtm::DTMWSFilter> p3, jboolean p4, jboolean p5) { return call_method<"getDTM", jni::ref<com::sun::org::apache::xml::internal::dtm::DTM>>(p1, p2, p3, p4, p5); }
	jni::ref<com::sun::org::apache::xml::internal::dtm::DTM> getDTM(jni::ref<javax::xml::transform::Source> p1, jboolean p2, jni::ref<com::sun::org::apache::xml::internal::dtm::DTMWSFilter> p3, jboolean p4, jboolean p5, jboolean p6) { return call_method<"getDTM", jni::ref<com::sun::org::apache::xml::internal::dtm::DTM>>(p1, p2, p3, p4, p5, p6); }
	jni::ref<com::sun::org::apache::xml::internal::dtm::DTM> getDTM(jni::ref<javax::xml::transform::Source> p1, jboolean p2, jni::ref<com::sun::org::apache::xml::internal::dtm::DTMWSFilter> p3, jboolean p4, jboolean p5, jboolean p6, jboolean p7) { return call_method<"getDTM", jni::ref<com::sun::org::apache::xml::internal::dtm::DTM>>(p1, p2, p3, p4, p5, p6, p7); }
	jni::ref<com::sun::org::apache::xml::internal::dtm::DTM> getDTM(jni::ref<javax::xml::transform::Source> p1, jboolean p2, jni::ref<com::sun::org::apache::xml::internal::dtm::DTMWSFilter> p3, jboolean p4, jboolean p5, jboolean p6, jint p7, jboolean p8) { return call_method<"getDTM", jni::ref<com::sun::org::apache::xml::internal::dtm::DTM>>(p1, p2, p3, p4, p5, p6, p7, p8); }
	jni::ref<com::sun::org::apache::xml::internal::dtm::DTM> getDTM(jni::ref<javax::xml::transform::Source> p1, jboolean p2, jni::ref<com::sun::org::apache::xml::internal::dtm::DTMWSFilter> p3, jboolean p4, jboolean p5, jboolean p6, jint p7, jboolean p8, jboolean p9) { return call_method<"getDTM", jni::ref<com::sun::org::apache::xml::internal::dtm::DTM>>(p1, p2, p3, p4, p5, p6, p7, p8, p9); }

protected:

	XSLTCDTMManager(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_ORG_APACHE_XALAN_INTERNAL_XSLTC_DOM_XSLTCDTMMANAGER
