// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4_FWD
#define SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::renderscript { class Short4; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::renderscript::Short4>
{
	static constexpr fixed_string class_name = "android/renderscript/Short4";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4)
#define SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::renderscript::Short4 : public jni::object_base<"android/renderscript/Short4",
	java::lang::Object>
{
public:

	jshort w() { return get_field<"w", jshort>(); }
	void w(jshort v) { set_field<"w", jshort>(v); }
	jshort x() { return get_field<"x", jshort>(); }
	void x(jshort v) { set_field<"x", jshort>(v); }
	jshort y() { return get_field<"y", jshort>(); }
	void y(jshort v) { set_field<"y", jshort>(v); }
	jshort z() { return get_field<"z", jshort>(); }
	void z(jshort v) { set_field<"z", jshort>(v); }

	static jni::ref<android::renderscript::Short4> new_object() { return base_::new_object(); }
	static jni::ref<android::renderscript::Short4> new_object(jshort x, jshort y, jshort z, jshort w) { return base_::new_object(x, y, z, w); }

protected:

	Short4(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_RENDERSCRIPT_SHORT4
