// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_JAVA_AWT_CURSOR_FWD
#define SCAPIX_JAVA_API_JAVA_AWT_CURSOR_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::awt { class Cursor; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::awt::Cursor>
{
	static constexpr fixed_string class_name = "java/awt/Cursor";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_CURSOR_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_AWT_CURSOR)
#define SCAPIX_JAVA_API_JAVA_AWT_CURSOR

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::awt::Cursor : public jni::object_base<"java/awt/Cursor",
	java::lang::Object,
	java::io::Serializable>
{
public:

	static jint DEFAULT_CURSOR() { return get_static_field<"DEFAULT_CURSOR", jint>(); }
	static jint CROSSHAIR_CURSOR() { return get_static_field<"CROSSHAIR_CURSOR", jint>(); }
	static jint TEXT_CURSOR() { return get_static_field<"TEXT_CURSOR", jint>(); }
	static jint WAIT_CURSOR() { return get_static_field<"WAIT_CURSOR", jint>(); }
	static jint SW_RESIZE_CURSOR() { return get_static_field<"SW_RESIZE_CURSOR", jint>(); }
	static jint SE_RESIZE_CURSOR() { return get_static_field<"SE_RESIZE_CURSOR", jint>(); }
	static jint NW_RESIZE_CURSOR() { return get_static_field<"NW_RESIZE_CURSOR", jint>(); }
	static jint NE_RESIZE_CURSOR() { return get_static_field<"NE_RESIZE_CURSOR", jint>(); }
	static jint N_RESIZE_CURSOR() { return get_static_field<"N_RESIZE_CURSOR", jint>(); }
	static jint S_RESIZE_CURSOR() { return get_static_field<"S_RESIZE_CURSOR", jint>(); }
	static jint W_RESIZE_CURSOR() { return get_static_field<"W_RESIZE_CURSOR", jint>(); }
	static jint E_RESIZE_CURSOR() { return get_static_field<"E_RESIZE_CURSOR", jint>(); }
	static jint HAND_CURSOR() { return get_static_field<"HAND_CURSOR", jint>(); }
	static jint MOVE_CURSOR() { return get_static_field<"MOVE_CURSOR", jint>(); }
	static jint CUSTOM_CURSOR() { return get_static_field<"CUSTOM_CURSOR", jint>(); }

	static jni::ref<java::awt::Cursor> getPredefinedCursor(jint p1) { return call_static_method<"getPredefinedCursor", jni::ref<java::awt::Cursor>>(p1); }
	static jni::ref<java::awt::Cursor> getSystemCustomCursor(jni::ref<java::lang::String> p1) { return call_static_method<"getSystemCustomCursor", jni::ref<java::awt::Cursor>>(p1); }
	static jni::ref<java::awt::Cursor> getDefaultCursor() { return call_static_method<"getDefaultCursor", jni::ref<java::awt::Cursor>>(); }
	static jni::ref<java::awt::Cursor> new_object(jint p1) { return base_::new_object(p1); }
	jint getType() { return call_method<"getType", jint>(); }
	jni::ref<java::lang::String> getName() { return call_method<"getName", jni::ref<java::lang::String>>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }

protected:

	Cursor(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_CURSOR
