// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/sun/awt/SunGraphicsCallback.h>

#ifndef SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK_FWD
#define SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::awt { class GraphicsCallback; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::awt::GraphicsCallback>
{
	static constexpr fixed_string class_name = "java/awt/GraphicsCallback";
	using base_classes = std::tuple<scapix::java_api::sun::awt::SunGraphicsCallback>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK)
#define SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class java::awt::GraphicsCallback : public jni::object_base<"java/awt/GraphicsCallback",
	sun::awt::SunGraphicsCallback>
{
public:


protected:

	GraphicsCallback(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_GRAPHICSCALLBACK
