// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/javax/management/MBeanFeatureInfo.h>
#include <scapix/java_api/java/lang/Cloneable.h>

#ifndef SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO_FWD
#define SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace javax::management {

class MBeanOperationInfo;

} // namespace javax::management
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::management::MBeanOperationInfo>
{
	static constexpr fixed_string class_name = "javax/management/MBeanOperationInfo";
	using base_classes = std::tuple<scapix::java_api::javax::management::MBeanFeatureInfo, scapix::java_api::java::lang::Cloneable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO
#define SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/lang/reflect/Method.h>
#include <scapix/java_api/javax/management/Descriptor.h>
#include <scapix/java_api/javax/management/MBeanParameterInfo.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::management::MBeanOperationInfo : public jni::object_base<"javax/management/MBeanOperationInfo",
	javax::management::MBeanFeatureInfo,
	java::lang::Cloneable>
{
public:

	static jint INFO() { return get_static_field<"INFO", jint>(); }
	static jint ACTION() { return get_static_field<"ACTION", jint>(); }
	static jint ACTION_INFO() { return get_static_field<"ACTION_INFO", jint>(); }
	static jint UNKNOWN() { return get_static_field<"UNKNOWN", jint>(); }

	static jni::ref<javax::management::MBeanOperationInfo> new_object(jni::ref<java::lang::String> description, jni::ref<java::lang::reflect::Method> method) { return object_base::new_object(description, method); }
	static jni::ref<javax::management::MBeanOperationInfo> new_object(jni::ref<java::lang::String> name, jni::ref<java::lang::String> description, jni::ref<jni::array<javax::management::MBeanParameterInfo>> signature, jni::ref<java::lang::String> type, jint impact) { return object_base::new_object(name, description, signature, type, impact); }
	static jni::ref<javax::management::MBeanOperationInfo> new_object(jni::ref<java::lang::String> name, jni::ref<java::lang::String> description, jni::ref<jni::array<javax::management::MBeanParameterInfo>> signature, jni::ref<java::lang::String> type, jint impact, jni::ref<javax::management::Descriptor> descriptor) { return object_base::new_object(name, description, signature, type, impact, descriptor); }
	jni::ref<java::lang::Object> clone() { return call_method<"clone", jni::ref<java::lang::Object>>(); }
	jni::ref<java::lang::String> getReturnType() { return call_method<"getReturnType", jni::ref<java::lang::String>>(); }
	jni::ref<jni::array<javax::management::MBeanParameterInfo>> getSignature() { return call_method<"getSignature", jni::ref<jni::array<javax::management::MBeanParameterInfo>>>(); }
	jint getImpact() { return call_method<"getImpact", jint>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	jboolean equals(jni::ref<java::lang::Object> o) { return call_method<"equals", jboolean>(o); }
	jint hashCode() { return call_method<"hashCode", jint>(); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_MANAGEMENT_MBEANOPERATIONINFO
#endif // SCAPIX_JAVA_API_FWD
