// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER_FWD
#define SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::lang::constant { class DynamicConstantDesc_CanonicalMapHolder; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::lang::constant::DynamicConstantDesc_CanonicalMapHolder>
{
	static constexpr fixed_string class_name = "java/lang/constant/DynamicConstantDesc$CanonicalMapHolder";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER)
#define SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class java::lang::constant::DynamicConstantDesc_CanonicalMapHolder : public jni::object_base<"java/lang/constant/DynamicConstantDesc$CanonicalMapHolder",
	java::lang::Object>
{
public:


protected:

	DynamicConstantDesc_CanonicalMapHolder(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_CONSTANT_DYNAMICCONSTANTDESC_CANONICALMAPHOLDER
