// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/sun/security/ssl/SSLPossession.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::security::ssl { class X509Authentication_X509Possession; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::ssl::X509Authentication_X509Possession>
{
	static constexpr fixed_string class_name = "sun/security/ssl/X509Authentication$X509Possession";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::sun::security::ssl::SSLPossession>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION)
#define SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class sun::security::ssl::X509Authentication_X509Possession : public jni::object_base<"sun/security/ssl/X509Authentication$X509Possession",
	java::lang::Object,
	sun::security::ssl::SSLPossession>
{
public:


protected:

	X509Authentication_X509Possession(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_SSL_X509AUTHENTICATION_X509POSSESSION
