// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER_FWD
#define SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::print { class PrinterInfo_Builder; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::print::PrinterInfo_Builder>
{
	static constexpr fixed_string class_name = "android/print/PrinterInfo$Builder";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER)
#define SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/print/PrinterCapabilitiesInfo.h>
#include <scapix/java_api/android/print/PrinterId.h>
#include <scapix/java_api/android/print/PrinterInfo.h>
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::print::PrinterInfo_Builder : public jni::object_base<"android/print/PrinterInfo$Builder",
	java::lang::Object>
{
public:

	static jni::ref<android::print::PrinterInfo_Builder> new_object(jni::ref<android::print::PrinterId> printerId, jni::ref<java::lang::String> name, jint status) { return base_::new_object(printerId, name, status); }
	static jni::ref<android::print::PrinterInfo_Builder> new_object(jni::ref<android::print::PrinterInfo> other) { return base_::new_object(other); }
	jni::ref<android::print::PrinterInfo_Builder> setStatus(jint status) { return call_method<"setStatus", jni::ref<android::print::PrinterInfo_Builder>>(status); }
	jni::ref<android::print::PrinterInfo_Builder> setName(jni::ref<java::lang::String> name) { return call_method<"setName", jni::ref<android::print::PrinterInfo_Builder>>(name); }
	jni::ref<android::print::PrinterInfo_Builder> setDescription(jni::ref<java::lang::String> description) { return call_method<"setDescription", jni::ref<android::print::PrinterInfo_Builder>>(description); }
	jni::ref<android::print::PrinterInfo_Builder> setCapabilities(jni::ref<android::print::PrinterCapabilitiesInfo> capabilities) { return call_method<"setCapabilities", jni::ref<android::print::PrinterInfo_Builder>>(capabilities); }
	jni::ref<android::print::PrinterInfo> build() { return call_method<"build", jni::ref<android::print::PrinterInfo>>(); }

protected:

	PrinterInfo_Builder(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PRINT_PRINTERINFO_BUILDER
