// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/com/sun/jdi/Mirror.h>
#include <scapix/java_api/com/sun/jdi/Locatable.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME_FWD
#define SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace com::sun::jdi {

class StackFrame;

} // namespace com::sun::jdi
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::jdi::StackFrame>
{
	static constexpr fixed_string class_name = "com/sun/jdi/StackFrame";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::com::sun::jdi::Mirror, scapix::java_api::com::sun::jdi::Locatable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME
#define SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/com/sun/jdi/LocalVariable.h>
#include <scapix/java_api/com/sun/jdi/Location.h>
#include <scapix/java_api/com/sun/jdi/ObjectReference.h>
#include <scapix/java_api/com/sun/jdi/ThreadReference.h>
#include <scapix/java_api/com/sun/jdi/Value.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/List.h>
#include <scapix/java_api/java/util/Map.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::jdi::StackFrame : public jni::object_base<"com/sun/jdi/StackFrame",
	java::lang::Object,
	com::sun::jdi::Mirror,
	com::sun::jdi::Locatable>
{
public:

	jni::ref<com::sun::jdi::Location> location() { return call_method<"location", jni::ref<com::sun::jdi::Location>>(); }
	jni::ref<com::sun::jdi::ThreadReference> thread() { return call_method<"thread", jni::ref<com::sun::jdi::ThreadReference>>(); }
	jni::ref<com::sun::jdi::ObjectReference> thisObject() { return call_method<"thisObject", jni::ref<com::sun::jdi::ObjectReference>>(); }
	jni::ref<java::util::List> visibleVariables() { return call_method<"visibleVariables", jni::ref<java::util::List>>(); }
	jni::ref<com::sun::jdi::LocalVariable> visibleVariableByName(jni::ref<java::lang::String> p1) { return call_method<"visibleVariableByName", jni::ref<com::sun::jdi::LocalVariable>>(p1); }
	jni::ref<com::sun::jdi::Value> getValue(jni::ref<com::sun::jdi::LocalVariable> p1) { return call_method<"getValue", jni::ref<com::sun::jdi::Value>>(p1); }
	jni::ref<java::util::Map> getValues(jni::ref<java::util::List> p1) { return call_method<"getValues", jni::ref<java::util::Map>>(p1); }
	void setValue(jni::ref<com::sun::jdi::LocalVariable> p1, jni::ref<com::sun::jdi::Value> p2) { return call_method<"setValue", void>(p1, p2); }
	jni::ref<java::util::List> getArgumentValues() { return call_method<"getArgumentValues", jni::ref<java::util::List>>(); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JDI_STACKFRAME
#endif // SCAPIX_JAVA_API_FWD
