// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/IllegalStateException.h>

#ifndef SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION_FWD
#define SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::nio::channels { class NonWritableChannelException; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::nio::channels::NonWritableChannelException>
{
	static constexpr fixed_string class_name = "java/nio/channels/NonWritableChannelException";
	using base_classes = std::tuple<scapix::java_api::java::lang::IllegalStateException>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION)
#define SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::nio::channels::NonWritableChannelException : public jni::object_base<"java/nio/channels/NonWritableChannelException",
	java::lang::IllegalStateException>
{
public:

	static jni::ref<java::nio::channels::NonWritableChannelException> new_object() { return base_::new_object(); }

protected:

	NonWritableChannelException(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_NIO_CHANNELS_NONWRITABLECHANNELEXCEPTION
