// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/com/sun/jmx/snmp/SnmpPdu.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET_FWD
#define SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::jmx::snmp { class SnmpPduPacket; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::jmx::snmp::SnmpPduPacket>
{
	static constexpr fixed_string class_name = "com/sun/jmx/snmp/SnmpPduPacket";
	using base_classes = std::tuple<scapix::java_api::com::sun::jmx::snmp::SnmpPdu, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET)
#define SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::jmx::snmp::SnmpPduPacket : public jni::object_base<"com/sun/jmx/snmp/SnmpPduPacket",
	com::sun::jmx::snmp::SnmpPdu,
	java::io::Serializable>
{
public:

	jni::ref<jni::array<jbyte>> community() { return get_field<"community", jni::ref<jni::array<jbyte>>>(); }
	void community(jni::ref<jni::array<jbyte>> v) { set_field<"community", jni::ref<jni::array<jbyte>>>(v); }

	static jni::ref<com::sun::jmx::snmp::SnmpPduPacket> new_object() { return base_::new_object(); }

protected:

	SnmpPduPacket(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JMX_SNMP_SNMPPDUPACKET
