// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR_FWD
#define SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::management { class Sensor; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::management::Sensor>
{
	static constexpr fixed_string class_name = "sun/management/Sensor";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR)
#define SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/lang/management/MemoryUsage.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::management::Sensor : public jni::object_base<"sun/management/Sensor",
	java::lang::Object>
{
public:

	static jni::ref<sun::management::Sensor> new_object(jni::ref<java::lang::String> p1) { return base_::new_object(p1); }
	jni::ref<java::lang::String> getName() { return call_method<"getName", jni::ref<java::lang::String>>(); }
	jlong getCount() { return call_method<"getCount", jlong>(); }
	jboolean isOn() { return call_method<"isOn", jboolean>(); }
	void trigger() { return call_method<"trigger", void>(); }
	void trigger(jint p1) { return call_method<"trigger", void>(p1); }
	void trigger(jint p1, jni::ref<java::lang::management::MemoryUsage> p2) { return call_method<"trigger", void>(p1, p2); }
	void clear() { return call_method<"clear", void>(); }
	void clear(jint p1) { return call_method<"clear", void>(p1); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }

protected:

	Sensor(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_MANAGEMENT_SENSOR
