// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::security::provider { class NativePRNG_NonBlocking; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::provider::NativePRNG_NonBlocking>
{
	static constexpr fixed_string class_name = "sun/security/provider/NativePRNG$NonBlocking";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING)
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::security::provider::NativePRNG_NonBlocking : public jni::object_base<"sun/security/provider/NativePRNG$NonBlocking",
	java::lang::Object>
{
public:

	static jni::ref<sun::security::provider::NativePRNG_NonBlocking> new_object() { return base_::new_object(); }

protected:

	NativePRNG_NonBlocking(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_NATIVEPRNG_NONBLOCKING
