// Generated by Scapix Java API 2.1
// https://www.scapix.com

#include <scapix/java_api/java/lang/Record.h>

#ifndef SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS_FWD
#define SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api { namespace java::lang::runtime { class SwitchBootstraps_TypePairs; }}

template<>
struct scapix::jni::object_traits<scapix::java_api::java::lang::runtime::SwitchBootstraps_TypePairs>
{
	static constexpr fixed_string class_name = "java/lang/runtime/SwitchBootstraps$TypePairs";
	using base_classes = std::tuple<scapix::java_api::java::lang::Record>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS)
#define SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Class.h>
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/Map.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class java::lang::runtime::SwitchBootstraps_TypePairs : public jni::object_base<"java/lang/runtime/SwitchBootstraps$TypePairs",
	java::lang::Record>
{
public:

	static jni::ref<java::lang::runtime::SwitchBootstraps_TypePairs> of(jni::ref<java::lang::Class> from, jni::ref<java::lang::Class> to) { return call_static_method<"of", jni::ref<java::lang::runtime::SwitchBootstraps_TypePairs>>(from, to); }
	jint hashCode() { return call_method<"hashCode", jint>(); }
	jboolean equals(jni::ref<java::lang::Object> other) { return call_method<"equals", jboolean>(other); }
	static jni::ref<java::util::Map> initialize() { return call_static_method<"initialize", jni::ref<java::util::Map>>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	jni::ref<java::lang::Class> from() { return call_method<"from", jni::ref<java::lang::Class>>(); }
	jni::ref<java::lang::Class> to() { return call_method<"to", jni::ref<java::lang::Class>>(); }

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_RUNTIME_SWITCHBOOTSTRAPS_TYPEPAIRS
