// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::swing::plaf::basic { class BasicBorders; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::plaf::basic::BasicBorders>
{
	static constexpr fixed_string class_name = "javax/swing/plaf/basic/BasicBorders";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS)
#define SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/javax/swing/border/Border.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_RolloverButtonBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_ButtonBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_ToggleButtonBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_RadioButtonBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_MenuBarBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_MarginBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_FieldBorder.h>
#include <scapix/java_api/javax/swing/plaf/basic/BasicBorders_SplitPaneBorder.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::swing::plaf::basic::BasicBorders : public jni::object_base<"javax/swing/plaf/basic/BasicBorders",
	java::lang::Object>
{
public:

	using RolloverButtonBorder = BasicBorders_RolloverButtonBorder;
	using ButtonBorder = BasicBorders_ButtonBorder;
	using ToggleButtonBorder = BasicBorders_ToggleButtonBorder;
	using RadioButtonBorder = BasicBorders_RadioButtonBorder;
	using MenuBarBorder = BasicBorders_MenuBarBorder;
	using MarginBorder = BasicBorders_MarginBorder;
	using FieldBorder = BasicBorders_FieldBorder;
	using SplitPaneBorder = BasicBorders_SplitPaneBorder;

	static jni::ref<javax::swing::plaf::basic::BasicBorders> new_object() { return base_::new_object(); }
	static jni::ref<javax::swing::border::Border> getButtonBorder() { return call_static_method<"getButtonBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getRadioButtonBorder() { return call_static_method<"getRadioButtonBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getToggleButtonBorder() { return call_static_method<"getToggleButtonBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getMenuBarBorder() { return call_static_method<"getMenuBarBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getSplitPaneBorder() { return call_static_method<"getSplitPaneBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getSplitPaneDividerBorder() { return call_static_method<"getSplitPaneDividerBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getTextFieldBorder() { return call_static_method<"getTextFieldBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getProgressBarBorder() { return call_static_method<"getProgressBarBorder", jni::ref<javax::swing::border::Border>>(); }
	static jni::ref<javax::swing::border::Border> getInternalFrameBorder() { return call_static_method<"getInternalFrameBorder", jni::ref<javax::swing::border::Border>>(); }

protected:

	BasicBorders(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_PLAF_BASIC_BASICBORDERS
