// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/util/spi/LocaleServiceProvider.h>

#ifndef SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER_FWD
#define SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::text::spi { class JavaTimeDateTimePatternProvider; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::text::spi::JavaTimeDateTimePatternProvider>
{
	static constexpr fixed_string class_name = "sun/text/spi/JavaTimeDateTimePatternProvider";
	using base_classes = std::tuple<scapix::java_api::java::util::spi::LocaleServiceProvider>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER)
#define SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/Locale.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::text::spi::JavaTimeDateTimePatternProvider : public jni::object_base<"sun/text/spi/JavaTimeDateTimePatternProvider",
	java::util::spi::LocaleServiceProvider>
{
public:

	jni::ref<java::lang::String> getJavaTimeDateTimePattern(jint p1, jint p2, jni::ref<java::lang::String> p3, jni::ref<java::util::Locale> p4) { return call_method<"getJavaTimeDateTimePattern", jni::ref<java::lang::String>>(p1, p2, p3, p4); }
	jni::ref<java::lang::String> getJavaTimeDateTimePattern(jni::ref<java::lang::String> requestedTemplate, jni::ref<java::lang::String> calType, jni::ref<java::util::Locale> locale) { return call_method<"getJavaTimeDateTimePattern", jni::ref<java::lang::String>>(requestedTemplate, calType, locale); }

protected:

	JavaTimeDateTimePatternProvider(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_TEXT_SPI_JAVATIMEDATETIMEPATTERNPROVIDER
