// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/com/sun/corba/se/internal/iiop/ORB.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB_FWD
#define SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::corba::se::internal::POA { class POAORB; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::corba::se::internal::POA::POAORB>
{
	static constexpr fixed_string class_name = "com/sun/corba/se/internal/POA/POAORB";
	using base_classes = std::tuple<scapix::java_api::com::sun::corba::se::internal::iiop::ORB>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB)
#define SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::corba::se::internal::POA::POAORB : public jni::object_base<"com/sun/corba/se/internal/POA/POAORB",
	com::sun::corba::se::internal::iiop::ORB>
{
public:

	static jni::ref<com::sun::corba::se::internal::POA::POAORB> new_object() { return base_::new_object(); }

protected:

	POAORB(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_CORBA_SE_INTERNAL_POA_POAORB
