// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR_FWD
#define SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::awt { class AWTAccessor_MenuAccessor; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::awt::AWTAccessor_MenuAccessor>
{
	static constexpr fixed_string class_name = "sun/awt/AWTAccessor$MenuAccessor";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR)
#define SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/awt/Menu.h>
#include <scapix/java_api/java/util/Vector.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::awt::AWTAccessor_MenuAccessor : public jni::object_base<"sun/awt/AWTAccessor$MenuAccessor",
	java::lang::Object>
{
public:

	jni::ref<java::util::Vector> getItems(jni::ref<java::awt::Menu> p1) { return call_method<"getItems", jni::ref<java::util::Vector>>(p1); }

protected:

	AWTAccessor_MenuAccessor(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_AWT_AWTACCESSOR_MENUACCESSOR
