// Generated by Scapix Java API 2.1
// https://www.scapix.com

#include <scapix/java_api/java/lang/Record.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api { namespace sun::security::provider { class ML_DSA_ML_DSA_KeyPair; }}

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::provider::ML_DSA_ML_DSA_KeyPair>
{
	static constexpr fixed_string class_name = "sun/security/provider/ML_DSA$ML_DSA_KeyPair";
	using base_classes = std::tuple<scapix::java_api::java::lang::Record>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR)
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/sun/security/provider/ML_DSA_ML_DSA_PrivateKey.h>
#include <scapix/java_api/sun/security/provider/ML_DSA_ML_DSA_PublicKey.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::security::provider::ML_DSA_ML_DSA_KeyPair : public jni::object_base<"sun/security/provider/ML_DSA$ML_DSA_KeyPair",
	java::lang::Record>
{
public:

	static jni::ref<sun::security::provider::ML_DSA_ML_DSA_KeyPair> new_object(jni::ref<sun::security::provider::ML_DSA_ML_DSA_PrivateKey> privateKey, jni::ref<sun::security::provider::ML_DSA_ML_DSA_PublicKey> publicKey) { return object_base::new_object(privateKey, publicKey); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	jint hashCode() { return call_method<"hashCode", jint>(); }
	jboolean equals(jni::ref<java::lang::Object> o) { return call_method<"equals", jboolean>(o); }
	jni::ref<sun::security::provider::ML_DSA_ML_DSA_PrivateKey> privateKey() { return call_method<"privateKey", jni::ref<sun::security::provider::ML_DSA_ML_DSA_PrivateKey>>(); }
	jni::ref<sun::security::provider::ML_DSA_ML_DSA_PublicKey> publicKey() { return call_method<"publicKey", jni::ref<sun::security::provider::ML_DSA_ML_DSA_PublicKey>>(); }

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_ML_DSA_ML_DSA_KEYPAIR
