// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/Runnable.h>

#ifndef SCAPIX_JAVA_API_JAVA_LANG_THREAD_FWD
#define SCAPIX_JAVA_API_JAVA_LANG_THREAD_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::lang { class Thread; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::lang::Thread>
{
	static constexpr fixed_string class_name = "java/lang/Thread";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::java::lang::Runnable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_THREAD_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_LANG_THREAD)
#define SCAPIX_JAVA_API_JAVA_LANG_THREAD

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/ClassLoader.h>
#include <scapix/java_api/java/lang/StackTraceElement.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/lang/Thread_State.h>
#include <scapix/java_api/java/lang/Thread_UncaughtExceptionHandler.h>
#include <scapix/java_api/java/lang/ThreadGroup.h>
#include <scapix/java_api/java/lang/Throwable.h>
#include <scapix/java_api/java/util/Map.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::lang::Thread : public jni::object_base<"java/lang/Thread",
	java::lang::Object,
	java::lang::Runnable>
{
public:

	using UncaughtExceptionHandler = Thread_UncaughtExceptionHandler;
	using State = Thread_State;

	static jint MAX_PRIORITY() { return get_static_field<"MAX_PRIORITY", jint>(); }
	static jint MIN_PRIORITY() { return get_static_field<"MIN_PRIORITY", jint>(); }
	static jint NORM_PRIORITY() { return get_static_field<"NORM_PRIORITY", jint>(); }

	static jni::ref<java::lang::Thread> new_object() { return base_::new_object(); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::Runnable> runnable) { return base_::new_object(runnable); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::Runnable> runnable, jni::ref<java::lang::String> threadName) { return base_::new_object(runnable, threadName); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::String> threadName) { return base_::new_object(threadName); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::ThreadGroup> group, jni::ref<java::lang::Runnable> runnable) { return base_::new_object(group, runnable); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::ThreadGroup> group, jni::ref<java::lang::Runnable> runnable, jni::ref<java::lang::String> threadName) { return base_::new_object(group, runnable, threadName); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::ThreadGroup> group, jni::ref<java::lang::String> threadName) { return base_::new_object(group, threadName); }
	static jni::ref<java::lang::Thread> new_object(jni::ref<java::lang::ThreadGroup> group, jni::ref<java::lang::Runnable> runnable, jni::ref<java::lang::String> threadName, jlong stackSize) { return base_::new_object(group, runnable, threadName, stackSize); }
	static jint activeCount() { return call_static_method<"activeCount", jint>(); }
	void checkAccess() { return call_method<"checkAccess", void>(); }
	jint countStackFrames() { return call_method<"countStackFrames", jint>(); }
	static jni::ref<java::lang::Thread> currentThread() { return call_static_method<"currentThread", jni::ref<java::lang::Thread>>(); }
	void destroy() { return call_method<"destroy", void>(); }
	static void dumpStack() { return call_static_method<"dumpStack", void>(); }
	static jint enumerate(jni::ref<jni::array<java::lang::Thread>> threads) { return call_static_method<"enumerate", jint>(threads); }
	static jni::ref<java::util::Map> getAllStackTraces() { return call_static_method<"getAllStackTraces", jni::ref<java::util::Map>>(); }
	jni::ref<java::lang::ClassLoader> getContextClassLoader() { return call_method<"getContextClassLoader", jni::ref<java::lang::ClassLoader>>(); }
	static jni::ref<java::lang::Thread_UncaughtExceptionHandler> getDefaultUncaughtExceptionHandler() { return call_static_method<"getDefaultUncaughtExceptionHandler", jni::ref<java::lang::Thread_UncaughtExceptionHandler>>(); }
	jlong getId() { return call_method<"getId", jlong>(); }
	jni::ref<java::lang::String> getName() { return call_method<"getName", jni::ref<java::lang::String>>(); }
	jint getPriority() { return call_method<"getPriority", jint>(); }
	jni::ref<jni::array<java::lang::StackTraceElement>> getStackTrace() { return call_method<"getStackTrace", jni::ref<jni::array<java::lang::StackTraceElement>>>(); }
	jni::ref<java::lang::Thread_State> getState() { return call_method<"getState", jni::ref<java::lang::Thread_State>>(); }
	jni::ref<java::lang::ThreadGroup> getThreadGroup() { return call_method<"getThreadGroup", jni::ref<java::lang::ThreadGroup>>(); }
	jni::ref<java::lang::Thread_UncaughtExceptionHandler> getUncaughtExceptionHandler() { return call_method<"getUncaughtExceptionHandler", jni::ref<java::lang::Thread_UncaughtExceptionHandler>>(); }
	void interrupt() { return call_method<"interrupt", void>(); }
	static jboolean interrupted() { return call_static_method<"interrupted", jboolean>(); }
	jboolean isAlive() { return call_method<"isAlive", jboolean>(); }
	jboolean isDaemon() { return call_method<"isDaemon", jboolean>(); }
	jboolean isInterrupted() { return call_method<"isInterrupted", jboolean>(); }
	void join() { return call_method<"join", void>(); }
	void join(jlong millis) { return call_method<"join", void>(millis); }
	void join(jlong millis, jint p2) { return call_method<"join", void>(millis, p2); }
	void resume() { return call_method<"resume", void>(); }
	void run() { return call_method<"run", void>(); }
	void setContextClassLoader(jni::ref<java::lang::ClassLoader> cl) { return call_method<"setContextClassLoader", void>(cl); }
	void setDaemon(jboolean isDaemon) { return call_method<"setDaemon", void>(isDaemon); }
	static void setDefaultUncaughtExceptionHandler(jni::ref<java::lang::Thread_UncaughtExceptionHandler> handler) { return call_static_method<"setDefaultUncaughtExceptionHandler", void>(handler); }
	void setName(jni::ref<java::lang::String> threadName) { return call_method<"setName", void>(threadName); }
	void setPriority(jint priority) { return call_method<"setPriority", void>(priority); }
	void setUncaughtExceptionHandler(jni::ref<java::lang::Thread_UncaughtExceptionHandler> handler) { return call_method<"setUncaughtExceptionHandler", void>(handler); }
	static void sleep(jlong time) { return call_static_method<"sleep", void>(time); }
	static void sleep(jlong millis, jint p2) { return call_static_method<"sleep", void>(millis, p2); }
	void start() { return call_method<"start", void>(); }
	void stop() { return call_method<"stop", void>(); }
	void stop(jni::ref<java::lang::Throwable> throwable) { return call_method<"stop", void>(throwable); }
	void suspend() { return call_method<"suspend", void>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	static void yield() { return call_static_method<"yield", void>(); }
	static jboolean holdsLock(jni::ref<java::lang::Object> object) { return call_static_method<"holdsLock", jboolean>(object); }

protected:

	Thread(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_THREAD
