// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/AbstractStringBuilder.h>
#include <scapix/java_api/java/lang/Appendable.h>
#include <scapix/java_api/java/io/Serializable.h>
#include <scapix/java_api/java/lang/Comparable.h>
#include <scapix/java_api/java/lang/CharSequence.h>

#ifndef SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER_FWD
#define SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::lang { class StringBuffer; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::lang::StringBuffer>
{
	static constexpr fixed_string class_name = "java/lang/StringBuffer";
	using base_classes = std::tuple<scapix::java_api::java::lang::AbstractStringBuilder, scapix::java_api::java::lang::Appendable, scapix::java_api::java::io::Serializable, scapix::java_api::java::lang::Comparable, scapix::java_api::java::lang::CharSequence>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER)
#define SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::lang::StringBuffer : public jni::object_base<"java/lang/StringBuffer",
	java::lang::AbstractStringBuilder,
	java::lang::Appendable,
	java::io::Serializable,
	java::lang::Comparable,
	java::lang::CharSequence>
{
public:

	static jni::ref<java::lang::StringBuffer> new_object() { return base_::new_object(); }
	static jni::ref<java::lang::StringBuffer> new_object(jint capacity) { return base_::new_object(capacity); }
	static jni::ref<java::lang::StringBuffer> new_object(jni::ref<java::lang::String> str) { return base_::new_object(str); }
	static jni::ref<java::lang::StringBuffer> new_object(jni::ref<java::lang::CharSequence> seq) { return base_::new_object(seq); }
	jint compareTo(jni::ref<java::lang::StringBuffer> another) { return call_method<"compareTo", jint>(another); }
	jint length() { return call_method<"length", jint>(); }
	jint capacity() { return call_method<"capacity", jint>(); }
	void ensureCapacity(jint minimumCapacity) { return call_method<"ensureCapacity", void>(minimumCapacity); }
	void trimToSize() { return call_method<"trimToSize", void>(); }
	void setLength(jint newLength) { return call_method<"setLength", void>(newLength); }
	jchar charAt(jint index) { return call_method<"charAt", jchar>(index); }
	jint codePointAt(jint index) { return call_method<"codePointAt", jint>(index); }
	jint codePointBefore(jint index) { return call_method<"codePointBefore", jint>(index); }
	jint codePointCount(jint beginIndex, jint endIndex) { return call_method<"codePointCount", jint>(beginIndex, endIndex); }
	jint offsetByCodePoints(jint index, jint codePointOffset) { return call_method<"offsetByCodePoints", jint>(index, codePointOffset); }
	void getChars(jint srcBegin, jint srcEnd, jni::ref<jni::array<jchar>> dst, jint dstBegin) { return call_method<"getChars", void>(srcBegin, srcEnd, dst, dstBegin); }
	void setCharAt(jint index, jchar ch) { return call_method<"setCharAt", void>(index, ch); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<java::lang::Object> obj) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(obj); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<java::lang::String> str) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(str); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<java::lang::StringBuffer> sb) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(sb); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<java::lang::CharSequence> s) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(s); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<java::lang::CharSequence> s, jint start, jint end) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(s, start, end); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<jni::array<jchar>> str) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(str); }
	jni::ref<java::lang::StringBuffer> append(jni::ref<jni::array<jchar>> str, jint offset, jint len) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(str, offset, len); }
	jni::ref<java::lang::StringBuffer> append(jboolean b) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(b); }
	jni::ref<java::lang::StringBuffer> append(jchar c) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(c); }
	jni::ref<java::lang::StringBuffer> append(jint i) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(i); }
	jni::ref<java::lang::StringBuffer> appendCodePoint(jint codePoint) { return call_method<"appendCodePoint", jni::ref<java::lang::StringBuffer>>(codePoint); }
	jni::ref<java::lang::StringBuffer> append(jlong lng) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(lng); }
	jni::ref<java::lang::StringBuffer> append(jfloat f) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(f); }
	jni::ref<java::lang::StringBuffer> append(jdouble d) { return call_method<"append", jni::ref<java::lang::StringBuffer>>(d); }
	jni::ref<java::lang::StringBuffer> delete_(jint start, jint end) { return call_method<"delete", jni::ref<java::lang::StringBuffer>>(start, end); }
	jni::ref<java::lang::StringBuffer> deleteCharAt(jint index) { return call_method<"deleteCharAt", jni::ref<java::lang::StringBuffer>>(index); }
	jni::ref<java::lang::StringBuffer> replace(jint start, jint end, jni::ref<java::lang::String> str) { return call_method<"replace", jni::ref<java::lang::StringBuffer>>(start, end, str); }
	jni::ref<java::lang::String> substring(jint start) { return call_method<"substring", jni::ref<java::lang::String>>(start); }
	jni::ref<java::lang::CharSequence> subSequence(jint start, jint end) { return call_method<"subSequence", jni::ref<java::lang::CharSequence>>(start, end); }
	jni::ref<java::lang::String> substring(jint start, jint end) { return call_method<"substring", jni::ref<java::lang::String>>(start, end); }
	jni::ref<java::lang::StringBuffer> insert(jint index, jni::ref<jni::array<jchar>> str, jint offset, jint len) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(index, str, offset, len); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jni::ref<java::lang::Object> obj) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, obj); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jni::ref<java::lang::String> str) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, str); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jni::ref<jni::array<jchar>> str) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, str); }
	jni::ref<java::lang::StringBuffer> insert(jint dstOffset, jni::ref<java::lang::CharSequence> s) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(dstOffset, s); }
	jni::ref<java::lang::StringBuffer> insert(jint dstOffset, jni::ref<java::lang::CharSequence> s, jint start, jint end) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(dstOffset, s, start, end); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jboolean b) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, b); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jchar c) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, c); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jint i) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, i); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jlong l) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, l); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jfloat f) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, f); }
	jni::ref<java::lang::StringBuffer> insert(jint offset, jdouble d) { return call_method<"insert", jni::ref<java::lang::StringBuffer>>(offset, d); }
	jint indexOf(jni::ref<java::lang::String> str) { return call_method<"indexOf", jint>(str); }
	jint indexOf(jni::ref<java::lang::String> str, jint fromIndex) { return call_method<"indexOf", jint>(str, fromIndex); }
	jint lastIndexOf(jni::ref<java::lang::String> str) { return call_method<"lastIndexOf", jint>(str); }
	jint lastIndexOf(jni::ref<java::lang::String> str, jint fromIndex) { return call_method<"lastIndexOf", jint>(str, fromIndex); }
	jni::ref<java::lang::StringBuffer> reverse() { return call_method<"reverse", jni::ref<java::lang::StringBuffer>>(); }
	jni::ref<java::lang::StringBuffer> repeat(jint codePoint, jint count) { return call_method<"repeat", jni::ref<java::lang::StringBuffer>>(codePoint, count); }
	jni::ref<java::lang::StringBuffer> repeat(jni::ref<java::lang::CharSequence> cs, jint count) { return call_method<"repeat", jni::ref<java::lang::StringBuffer>>(cs, count); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }

protected:

	StringBuffer(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_LANG_STRINGBUFFER
