// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH_FWD
#define SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::icu::lang { class UCharacter_EastAsianWidth; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::icu::lang::UCharacter_EastAsianWidth>
{
	static constexpr fixed_string class_name = "android/icu/lang/UCharacter$EastAsianWidth";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH)
#define SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::icu::lang::UCharacter_EastAsianWidth : public jni::object_base<"android/icu/lang/UCharacter$EastAsianWidth",
	java::lang::Object>
{
public:

	static jint AMBIGUOUS() { return get_static_field<"AMBIGUOUS", jint>(); }
	static jint FULLWIDTH() { return get_static_field<"FULLWIDTH", jint>(); }
	static jint HALFWIDTH() { return get_static_field<"HALFWIDTH", jint>(); }
	static jint NARROW() { return get_static_field<"NARROW", jint>(); }
	static jint NEUTRAL() { return get_static_field<"NEUTRAL", jint>(); }
	static jint WIDE() { return get_static_field<"WIDE", jint>(); }


protected:

	UCharacter_EastAsianWidth(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_ICU_LANG_UCHARACTER_EASTASIANWIDTH
