// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER_FWD
#define SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::hardware { class TriggerEventListener; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::hardware::TriggerEventListener>
{
	static constexpr fixed_string class_name = "android/hardware/TriggerEventListener";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER)
#define SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/hardware/TriggerEvent.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::hardware::TriggerEventListener : public jni::object_base<"android/hardware/TriggerEventListener",
	java::lang::Object>
{
public:

	static jni::ref<android::hardware::TriggerEventListener> new_object() { return base_::new_object(); }
	void onTrigger(jni::ref<android::hardware::TriggerEvent> p1) { return call_method<"onTrigger", void>(p1); }

protected:

	TriggerEventListener(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_HARDWARE_TRIGGEREVENTLISTENER
