// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::swing { class PopupFactory; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::PopupFactory>
{
	static constexpr fixed_string class_name = "javax/swing/PopupFactory";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY)
#define SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/awt/Component.h>
#include <scapix/java_api/javax/swing/Popup.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::swing::PopupFactory : public jni::object_base<"javax/swing/PopupFactory",
	java::lang::Object>
{
public:

	static jni::ref<javax::swing::PopupFactory> new_object() { return base_::new_object(); }
	static void setSharedInstance(jni::ref<javax::swing::PopupFactory> p1) { return call_static_method<"setSharedInstance", void>(p1); }
	static jni::ref<javax::swing::PopupFactory> getSharedInstance() { return call_static_method<"getSharedInstance", jni::ref<javax::swing::PopupFactory>>(); }
	jni::ref<javax::swing::Popup> getPopup(jni::ref<java::awt::Component> p1, jni::ref<java::awt::Component> p2, jint p3, jint p4) { return call_method<"getPopup", jni::ref<javax::swing::Popup>>(p1, p2, p3, p4); }

protected:

	PopupFactory(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_POPUPFACTORY
