// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS_FWD
#define SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::system { class OsConstants; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::system::OsConstants>
{
	static constexpr fixed_string class_name = "android/system/OsConstants";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS)
#define SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::system::OsConstants : public jni::object_base<"android/system/OsConstants",
	java::lang::Object>
{
public:

	static jint AF_INET() { return get_static_field<"AF_INET", jint>(); }
	static jint AF_INET6() { return get_static_field<"AF_INET6", jint>(); }
	static jint AF_NETLINK() { return get_static_field<"AF_NETLINK", jint>(); }
	static jint AF_PACKET() { return get_static_field<"AF_PACKET", jint>(); }
	static jint AF_UNIX() { return get_static_field<"AF_UNIX", jint>(); }
	static jint AF_UNSPEC() { return get_static_field<"AF_UNSPEC", jint>(); }
	static jint AI_ADDRCONFIG() { return get_static_field<"AI_ADDRCONFIG", jint>(); }
	static jint AI_ALL() { return get_static_field<"AI_ALL", jint>(); }
	static jint AI_CANONNAME() { return get_static_field<"AI_CANONNAME", jint>(); }
	static jint AI_NUMERICHOST() { return get_static_field<"AI_NUMERICHOST", jint>(); }
	static jint AI_NUMERICSERV() { return get_static_field<"AI_NUMERICSERV", jint>(); }
	static jint AI_PASSIVE() { return get_static_field<"AI_PASSIVE", jint>(); }
	static jint AI_V4MAPPED() { return get_static_field<"AI_V4MAPPED", jint>(); }
	static jint ARPHRD_ETHER() { return get_static_field<"ARPHRD_ETHER", jint>(); }
	static jint CAP_AUDIT_CONTROL() { return get_static_field<"CAP_AUDIT_CONTROL", jint>(); }
	static jint CAP_AUDIT_WRITE() { return get_static_field<"CAP_AUDIT_WRITE", jint>(); }
	static jint CAP_BLOCK_SUSPEND() { return get_static_field<"CAP_BLOCK_SUSPEND", jint>(); }
	static jint CAP_CHOWN() { return get_static_field<"CAP_CHOWN", jint>(); }
	static jint CAP_DAC_OVERRIDE() { return get_static_field<"CAP_DAC_OVERRIDE", jint>(); }
	static jint CAP_DAC_READ_SEARCH() { return get_static_field<"CAP_DAC_READ_SEARCH", jint>(); }
	static jint CAP_FOWNER() { return get_static_field<"CAP_FOWNER", jint>(); }
	static jint CAP_FSETID() { return get_static_field<"CAP_FSETID", jint>(); }
	static jint CAP_IPC_LOCK() { return get_static_field<"CAP_IPC_LOCK", jint>(); }
	static jint CAP_IPC_OWNER() { return get_static_field<"CAP_IPC_OWNER", jint>(); }
	static jint CAP_KILL() { return get_static_field<"CAP_KILL", jint>(); }
	static jint CAP_LAST_CAP() { return get_static_field<"CAP_LAST_CAP", jint>(); }
	static jint CAP_LEASE() { return get_static_field<"CAP_LEASE", jint>(); }
	static jint CAP_LINUX_IMMUTABLE() { return get_static_field<"CAP_LINUX_IMMUTABLE", jint>(); }
	static jint CAP_MAC_ADMIN() { return get_static_field<"CAP_MAC_ADMIN", jint>(); }
	static jint CAP_MAC_OVERRIDE() { return get_static_field<"CAP_MAC_OVERRIDE", jint>(); }
	static jint CAP_MKNOD() { return get_static_field<"CAP_MKNOD", jint>(); }
	static jint CAP_NET_ADMIN() { return get_static_field<"CAP_NET_ADMIN", jint>(); }
	static jint CAP_NET_BIND_SERVICE() { return get_static_field<"CAP_NET_BIND_SERVICE", jint>(); }
	static jint CAP_NET_BROADCAST() { return get_static_field<"CAP_NET_BROADCAST", jint>(); }
	static jint CAP_NET_RAW() { return get_static_field<"CAP_NET_RAW", jint>(); }
	static jint CAP_SETFCAP() { return get_static_field<"CAP_SETFCAP", jint>(); }
	static jint CAP_SETGID() { return get_static_field<"CAP_SETGID", jint>(); }
	static jint CAP_SETPCAP() { return get_static_field<"CAP_SETPCAP", jint>(); }
	static jint CAP_SETUID() { return get_static_field<"CAP_SETUID", jint>(); }
	static jint CAP_SYSLOG() { return get_static_field<"CAP_SYSLOG", jint>(); }
	static jint CAP_SYS_ADMIN() { return get_static_field<"CAP_SYS_ADMIN", jint>(); }
	static jint CAP_SYS_BOOT() { return get_static_field<"CAP_SYS_BOOT", jint>(); }
	static jint CAP_SYS_CHROOT() { return get_static_field<"CAP_SYS_CHROOT", jint>(); }
	static jint CAP_SYS_MODULE() { return get_static_field<"CAP_SYS_MODULE", jint>(); }
	static jint CAP_SYS_NICE() { return get_static_field<"CAP_SYS_NICE", jint>(); }
	static jint CAP_SYS_PACCT() { return get_static_field<"CAP_SYS_PACCT", jint>(); }
	static jint CAP_SYS_PTRACE() { return get_static_field<"CAP_SYS_PTRACE", jint>(); }
	static jint CAP_SYS_RAWIO() { return get_static_field<"CAP_SYS_RAWIO", jint>(); }
	static jint CAP_SYS_RESOURCE() { return get_static_field<"CAP_SYS_RESOURCE", jint>(); }
	static jint CAP_SYS_TIME() { return get_static_field<"CAP_SYS_TIME", jint>(); }
	static jint CAP_SYS_TTY_CONFIG() { return get_static_field<"CAP_SYS_TTY_CONFIG", jint>(); }
	static jint CAP_WAKE_ALARM() { return get_static_field<"CAP_WAKE_ALARM", jint>(); }
	static jint E2BIG() { return get_static_field<"E2BIG", jint>(); }
	static jint EACCES() { return get_static_field<"EACCES", jint>(); }
	static jint EADDRINUSE() { return get_static_field<"EADDRINUSE", jint>(); }
	static jint EADDRNOTAVAIL() { return get_static_field<"EADDRNOTAVAIL", jint>(); }
	static jint EAFNOSUPPORT() { return get_static_field<"EAFNOSUPPORT", jint>(); }
	static jint EAGAIN() { return get_static_field<"EAGAIN", jint>(); }
	static jint EAI_AGAIN() { return get_static_field<"EAI_AGAIN", jint>(); }
	static jint EAI_BADFLAGS() { return get_static_field<"EAI_BADFLAGS", jint>(); }
	static jint EAI_FAIL() { return get_static_field<"EAI_FAIL", jint>(); }
	static jint EAI_FAMILY() { return get_static_field<"EAI_FAMILY", jint>(); }
	static jint EAI_MEMORY() { return get_static_field<"EAI_MEMORY", jint>(); }
	static jint EAI_NODATA() { return get_static_field<"EAI_NODATA", jint>(); }
	static jint EAI_NONAME() { return get_static_field<"EAI_NONAME", jint>(); }
	static jint EAI_OVERFLOW() { return get_static_field<"EAI_OVERFLOW", jint>(); }
	static jint EAI_SERVICE() { return get_static_field<"EAI_SERVICE", jint>(); }
	static jint EAI_SOCKTYPE() { return get_static_field<"EAI_SOCKTYPE", jint>(); }
	static jint EAI_SYSTEM() { return get_static_field<"EAI_SYSTEM", jint>(); }
	static jint EALREADY() { return get_static_field<"EALREADY", jint>(); }
	static jint EBADF() { return get_static_field<"EBADF", jint>(); }
	static jint EBADMSG() { return get_static_field<"EBADMSG", jint>(); }
	static jint EBUSY() { return get_static_field<"EBUSY", jint>(); }
	static jint ECANCELED() { return get_static_field<"ECANCELED", jint>(); }
	static jint ECHILD() { return get_static_field<"ECHILD", jint>(); }
	static jint ECONNABORTED() { return get_static_field<"ECONNABORTED", jint>(); }
	static jint ECONNREFUSED() { return get_static_field<"ECONNREFUSED", jint>(); }
	static jint ECONNRESET() { return get_static_field<"ECONNRESET", jint>(); }
	static jint EDEADLK() { return get_static_field<"EDEADLK", jint>(); }
	static jint EDESTADDRREQ() { return get_static_field<"EDESTADDRREQ", jint>(); }
	static jint EDOM() { return get_static_field<"EDOM", jint>(); }
	static jint EDQUOT() { return get_static_field<"EDQUOT", jint>(); }
	static jint EEXIST() { return get_static_field<"EEXIST", jint>(); }
	static jint EFAULT() { return get_static_field<"EFAULT", jint>(); }
	static jint EFBIG() { return get_static_field<"EFBIG", jint>(); }
	static jint EHOSTUNREACH() { return get_static_field<"EHOSTUNREACH", jint>(); }
	static jint EIDRM() { return get_static_field<"EIDRM", jint>(); }
	static jint EILSEQ() { return get_static_field<"EILSEQ", jint>(); }
	static jint EINPROGRESS() { return get_static_field<"EINPROGRESS", jint>(); }
	static jint EINTR() { return get_static_field<"EINTR", jint>(); }
	static jint EINVAL() { return get_static_field<"EINVAL", jint>(); }
	static jint EIO() { return get_static_field<"EIO", jint>(); }
	static jint EISCONN() { return get_static_field<"EISCONN", jint>(); }
	static jint EISDIR() { return get_static_field<"EISDIR", jint>(); }
	static jint ELOOP() { return get_static_field<"ELOOP", jint>(); }
	static jint EMFILE() { return get_static_field<"EMFILE", jint>(); }
	static jint EMLINK() { return get_static_field<"EMLINK", jint>(); }
	static jint EMSGSIZE() { return get_static_field<"EMSGSIZE", jint>(); }
	static jint EMULTIHOP() { return get_static_field<"EMULTIHOP", jint>(); }
	static jint ENAMETOOLONG() { return get_static_field<"ENAMETOOLONG", jint>(); }
	static jint ENETDOWN() { return get_static_field<"ENETDOWN", jint>(); }
	static jint ENETRESET() { return get_static_field<"ENETRESET", jint>(); }
	static jint ENETUNREACH() { return get_static_field<"ENETUNREACH", jint>(); }
	static jint ENFILE() { return get_static_field<"ENFILE", jint>(); }
	static jint ENOBUFS() { return get_static_field<"ENOBUFS", jint>(); }
	static jint ENODATA() { return get_static_field<"ENODATA", jint>(); }
	static jint ENODEV() { return get_static_field<"ENODEV", jint>(); }
	static jint ENOENT() { return get_static_field<"ENOENT", jint>(); }
	static jint ENOEXEC() { return get_static_field<"ENOEXEC", jint>(); }
	static jint ENOLCK() { return get_static_field<"ENOLCK", jint>(); }
	static jint ENOLINK() { return get_static_field<"ENOLINK", jint>(); }
	static jint ENOMEM() { return get_static_field<"ENOMEM", jint>(); }
	static jint ENOMSG() { return get_static_field<"ENOMSG", jint>(); }
	static jint ENOPROTOOPT() { return get_static_field<"ENOPROTOOPT", jint>(); }
	static jint ENOSPC() { return get_static_field<"ENOSPC", jint>(); }
	static jint ENOSR() { return get_static_field<"ENOSR", jint>(); }
	static jint ENOSTR() { return get_static_field<"ENOSTR", jint>(); }
	static jint ENOSYS() { return get_static_field<"ENOSYS", jint>(); }
	static jint ENOTCONN() { return get_static_field<"ENOTCONN", jint>(); }
	static jint ENOTDIR() { return get_static_field<"ENOTDIR", jint>(); }
	static jint ENOTEMPTY() { return get_static_field<"ENOTEMPTY", jint>(); }
	static jint ENOTSOCK() { return get_static_field<"ENOTSOCK", jint>(); }
	static jint ENOTSUP() { return get_static_field<"ENOTSUP", jint>(); }
	static jint ENOTTY() { return get_static_field<"ENOTTY", jint>(); }
	static jint ENXIO() { return get_static_field<"ENXIO", jint>(); }
	static jint EOPNOTSUPP() { return get_static_field<"EOPNOTSUPP", jint>(); }
	static jint EOVERFLOW() { return get_static_field<"EOVERFLOW", jint>(); }
	static jint EPERM() { return get_static_field<"EPERM", jint>(); }
	static jint EPIPE() { return get_static_field<"EPIPE", jint>(); }
	static jint EPROTO() { return get_static_field<"EPROTO", jint>(); }
	static jint EPROTONOSUPPORT() { return get_static_field<"EPROTONOSUPPORT", jint>(); }
	static jint EPROTOTYPE() { return get_static_field<"EPROTOTYPE", jint>(); }
	static jint ERANGE() { return get_static_field<"ERANGE", jint>(); }
	static jint EROFS() { return get_static_field<"EROFS", jint>(); }
	static jint ESPIPE() { return get_static_field<"ESPIPE", jint>(); }
	static jint ESRCH() { return get_static_field<"ESRCH", jint>(); }
	static jint ESTALE() { return get_static_field<"ESTALE", jint>(); }
	static jint ETH_P_ALL() { return get_static_field<"ETH_P_ALL", jint>(); }
	static jint ETH_P_ARP() { return get_static_field<"ETH_P_ARP", jint>(); }
	static jint ETH_P_IP() { return get_static_field<"ETH_P_IP", jint>(); }
	static jint ETH_P_IPV6() { return get_static_field<"ETH_P_IPV6", jint>(); }
	static jint ETIME() { return get_static_field<"ETIME", jint>(); }
	static jint ETIMEDOUT() { return get_static_field<"ETIMEDOUT", jint>(); }
	static jint ETXTBSY() { return get_static_field<"ETXTBSY", jint>(); }
	static jint EXDEV() { return get_static_field<"EXDEV", jint>(); }
	static jint EXIT_FAILURE() { return get_static_field<"EXIT_FAILURE", jint>(); }
	static jint EXIT_SUCCESS() { return get_static_field<"EXIT_SUCCESS", jint>(); }
	static jint FD_CLOEXEC() { return get_static_field<"FD_CLOEXEC", jint>(); }
	static jint FIONREAD() { return get_static_field<"FIONREAD", jint>(); }
	static jint F_DUPFD() { return get_static_field<"F_DUPFD", jint>(); }
	static jint F_DUPFD_CLOEXEC() { return get_static_field<"F_DUPFD_CLOEXEC", jint>(); }
	static jint F_GETFD() { return get_static_field<"F_GETFD", jint>(); }
	static jint F_GETFL() { return get_static_field<"F_GETFL", jint>(); }
	static jint F_GETLK() { return get_static_field<"F_GETLK", jint>(); }
	static jint F_GETLK64() { return get_static_field<"F_GETLK64", jint>(); }
	static jint F_GETOWN() { return get_static_field<"F_GETOWN", jint>(); }
	static jint F_OK() { return get_static_field<"F_OK", jint>(); }
	static jint F_RDLCK() { return get_static_field<"F_RDLCK", jint>(); }
	static jint F_SETFD() { return get_static_field<"F_SETFD", jint>(); }
	static jint F_SETFL() { return get_static_field<"F_SETFL", jint>(); }
	static jint F_SETLK() { return get_static_field<"F_SETLK", jint>(); }
	static jint F_SETLK64() { return get_static_field<"F_SETLK64", jint>(); }
	static jint F_SETLKW() { return get_static_field<"F_SETLKW", jint>(); }
	static jint F_SETLKW64() { return get_static_field<"F_SETLKW64", jint>(); }
	static jint F_SETOWN() { return get_static_field<"F_SETOWN", jint>(); }
	static jint F_UNLCK() { return get_static_field<"F_UNLCK", jint>(); }
	static jint F_WRLCK() { return get_static_field<"F_WRLCK", jint>(); }
	static jint ICMP6_ECHO_REPLY() { return get_static_field<"ICMP6_ECHO_REPLY", jint>(); }
	static jint ICMP6_ECHO_REQUEST() { return get_static_field<"ICMP6_ECHO_REQUEST", jint>(); }
	static jint ICMP_ECHO() { return get_static_field<"ICMP_ECHO", jint>(); }
	static jint ICMP_ECHOREPLY() { return get_static_field<"ICMP_ECHOREPLY", jint>(); }
	static jint IFA_F_DADFAILED() { return get_static_field<"IFA_F_DADFAILED", jint>(); }
	static jint IFA_F_DEPRECATED() { return get_static_field<"IFA_F_DEPRECATED", jint>(); }
	static jint IFA_F_HOMEADDRESS() { return get_static_field<"IFA_F_HOMEADDRESS", jint>(); }
	static jint IFA_F_NODAD() { return get_static_field<"IFA_F_NODAD", jint>(); }
	static jint IFA_F_OPTIMISTIC() { return get_static_field<"IFA_F_OPTIMISTIC", jint>(); }
	static jint IFA_F_PERMANENT() { return get_static_field<"IFA_F_PERMANENT", jint>(); }
	static jint IFA_F_SECONDARY() { return get_static_field<"IFA_F_SECONDARY", jint>(); }
	static jint IFA_F_TEMPORARY() { return get_static_field<"IFA_F_TEMPORARY", jint>(); }
	static jint IFA_F_TENTATIVE() { return get_static_field<"IFA_F_TENTATIVE", jint>(); }
	static jint IFF_ALLMULTI() { return get_static_field<"IFF_ALLMULTI", jint>(); }
	static jint IFF_AUTOMEDIA() { return get_static_field<"IFF_AUTOMEDIA", jint>(); }
	static jint IFF_BROADCAST() { return get_static_field<"IFF_BROADCAST", jint>(); }
	static jint IFF_DEBUG() { return get_static_field<"IFF_DEBUG", jint>(); }
	static jint IFF_DYNAMIC() { return get_static_field<"IFF_DYNAMIC", jint>(); }
	static jint IFF_LOOPBACK() { return get_static_field<"IFF_LOOPBACK", jint>(); }
	static jint IFF_MASTER() { return get_static_field<"IFF_MASTER", jint>(); }
	static jint IFF_MULTICAST() { return get_static_field<"IFF_MULTICAST", jint>(); }
	static jint IFF_NOARP() { return get_static_field<"IFF_NOARP", jint>(); }
	static jint IFF_NOTRAILERS() { return get_static_field<"IFF_NOTRAILERS", jint>(); }
	static jint IFF_POINTOPOINT() { return get_static_field<"IFF_POINTOPOINT", jint>(); }
	static jint IFF_PORTSEL() { return get_static_field<"IFF_PORTSEL", jint>(); }
	static jint IFF_PROMISC() { return get_static_field<"IFF_PROMISC", jint>(); }
	static jint IFF_RUNNING() { return get_static_field<"IFF_RUNNING", jint>(); }
	static jint IFF_SLAVE() { return get_static_field<"IFF_SLAVE", jint>(); }
	static jint IFF_UP() { return get_static_field<"IFF_UP", jint>(); }
	static jint IPPROTO_ICMP() { return get_static_field<"IPPROTO_ICMP", jint>(); }
	static jint IPPROTO_ICMPV6() { return get_static_field<"IPPROTO_ICMPV6", jint>(); }
	static jint IPPROTO_IP() { return get_static_field<"IPPROTO_IP", jint>(); }
	static jint IPPROTO_IPV6() { return get_static_field<"IPPROTO_IPV6", jint>(); }
	static jint IPPROTO_RAW() { return get_static_field<"IPPROTO_RAW", jint>(); }
	static jint IPPROTO_TCP() { return get_static_field<"IPPROTO_TCP", jint>(); }
	static jint IPPROTO_UDP() { return get_static_field<"IPPROTO_UDP", jint>(); }
	static jint IPV6_CHECKSUM() { return get_static_field<"IPV6_CHECKSUM", jint>(); }
	static jint IPV6_MULTICAST_HOPS() { return get_static_field<"IPV6_MULTICAST_HOPS", jint>(); }
	static jint IPV6_MULTICAST_IF() { return get_static_field<"IPV6_MULTICAST_IF", jint>(); }
	static jint IPV6_MULTICAST_LOOP() { return get_static_field<"IPV6_MULTICAST_LOOP", jint>(); }
	static jint IPV6_RECVDSTOPTS() { return get_static_field<"IPV6_RECVDSTOPTS", jint>(); }
	static jint IPV6_RECVHOPLIMIT() { return get_static_field<"IPV6_RECVHOPLIMIT", jint>(); }
	static jint IPV6_RECVHOPOPTS() { return get_static_field<"IPV6_RECVHOPOPTS", jint>(); }
	static jint IPV6_RECVPKTINFO() { return get_static_field<"IPV6_RECVPKTINFO", jint>(); }
	static jint IPV6_RECVRTHDR() { return get_static_field<"IPV6_RECVRTHDR", jint>(); }
	static jint IPV6_RECVTCLASS() { return get_static_field<"IPV6_RECVTCLASS", jint>(); }
	static jint IPV6_TCLASS() { return get_static_field<"IPV6_TCLASS", jint>(); }
	static jint IPV6_UNICAST_HOPS() { return get_static_field<"IPV6_UNICAST_HOPS", jint>(); }
	static jint IPV6_V6ONLY() { return get_static_field<"IPV6_V6ONLY", jint>(); }
	static jint IP_MULTICAST_IF() { return get_static_field<"IP_MULTICAST_IF", jint>(); }
	static jint IP_MULTICAST_LOOP() { return get_static_field<"IP_MULTICAST_LOOP", jint>(); }
	static jint IP_MULTICAST_TTL() { return get_static_field<"IP_MULTICAST_TTL", jint>(); }
	static jint IP_TOS() { return get_static_field<"IP_TOS", jint>(); }
	static jint IP_TTL() { return get_static_field<"IP_TTL", jint>(); }
	static jint MAP_ANONYMOUS() { return get_static_field<"MAP_ANONYMOUS", jint>(); }
	static jint MAP_FIXED() { return get_static_field<"MAP_FIXED", jint>(); }
	static jint MAP_PRIVATE() { return get_static_field<"MAP_PRIVATE", jint>(); }
	static jint MAP_SHARED() { return get_static_field<"MAP_SHARED", jint>(); }
	static jint MCAST_BLOCK_SOURCE() { return get_static_field<"MCAST_BLOCK_SOURCE", jint>(); }
	static jint MCAST_JOIN_GROUP() { return get_static_field<"MCAST_JOIN_GROUP", jint>(); }
	static jint MCAST_JOIN_SOURCE_GROUP() { return get_static_field<"MCAST_JOIN_SOURCE_GROUP", jint>(); }
	static jint MCAST_LEAVE_GROUP() { return get_static_field<"MCAST_LEAVE_GROUP", jint>(); }
	static jint MCAST_LEAVE_SOURCE_GROUP() { return get_static_field<"MCAST_LEAVE_SOURCE_GROUP", jint>(); }
	static jint MCAST_UNBLOCK_SOURCE() { return get_static_field<"MCAST_UNBLOCK_SOURCE", jint>(); }
	static jint MCL_CURRENT() { return get_static_field<"MCL_CURRENT", jint>(); }
	static jint MCL_FUTURE() { return get_static_field<"MCL_FUTURE", jint>(); }
	static jint MFD_CLOEXEC() { return get_static_field<"MFD_CLOEXEC", jint>(); }
	static jint MSG_CTRUNC() { return get_static_field<"MSG_CTRUNC", jint>(); }
	static jint MSG_DONTROUTE() { return get_static_field<"MSG_DONTROUTE", jint>(); }
	static jint MSG_EOR() { return get_static_field<"MSG_EOR", jint>(); }
	static jint MSG_OOB() { return get_static_field<"MSG_OOB", jint>(); }
	static jint MSG_PEEK() { return get_static_field<"MSG_PEEK", jint>(); }
	static jint MSG_TRUNC() { return get_static_field<"MSG_TRUNC", jint>(); }
	static jint MSG_WAITALL() { return get_static_field<"MSG_WAITALL", jint>(); }
	static jint MS_ASYNC() { return get_static_field<"MS_ASYNC", jint>(); }
	static jint MS_INVALIDATE() { return get_static_field<"MS_INVALIDATE", jint>(); }
	static jint MS_SYNC() { return get_static_field<"MS_SYNC", jint>(); }
	static jint NETLINK_INET_DIAG() { return get_static_field<"NETLINK_INET_DIAG", jint>(); }
	static jint NETLINK_NETFILTER() { return get_static_field<"NETLINK_NETFILTER", jint>(); }
	static jint NETLINK_ROUTE() { return get_static_field<"NETLINK_ROUTE", jint>(); }
	static jint NI_DGRAM() { return get_static_field<"NI_DGRAM", jint>(); }
	static jint NI_NAMEREQD() { return get_static_field<"NI_NAMEREQD", jint>(); }
	static jint NI_NOFQDN() { return get_static_field<"NI_NOFQDN", jint>(); }
	static jint NI_NUMERICHOST() { return get_static_field<"NI_NUMERICHOST", jint>(); }
	static jint NI_NUMERICSERV() { return get_static_field<"NI_NUMERICSERV", jint>(); }
	static jint O_ACCMODE() { return get_static_field<"O_ACCMODE", jint>(); }
	static jint O_APPEND() { return get_static_field<"O_APPEND", jint>(); }
	static jint O_CLOEXEC() { return get_static_field<"O_CLOEXEC", jint>(); }
	static jint O_CREAT() { return get_static_field<"O_CREAT", jint>(); }
	static jint O_DSYNC() { return get_static_field<"O_DSYNC", jint>(); }
	static jint O_EXCL() { return get_static_field<"O_EXCL", jint>(); }
	static jint O_NOCTTY() { return get_static_field<"O_NOCTTY", jint>(); }
	static jint O_NOFOLLOW() { return get_static_field<"O_NOFOLLOW", jint>(); }
	static jint O_NONBLOCK() { return get_static_field<"O_NONBLOCK", jint>(); }
	static jint O_RDONLY() { return get_static_field<"O_RDONLY", jint>(); }
	static jint O_RDWR() { return get_static_field<"O_RDWR", jint>(); }
	static jint O_SYNC() { return get_static_field<"O_SYNC", jint>(); }
	static jint O_TRUNC() { return get_static_field<"O_TRUNC", jint>(); }
	static jint O_WRONLY() { return get_static_field<"O_WRONLY", jint>(); }
	static jint POLLERR() { return get_static_field<"POLLERR", jint>(); }
	static jint POLLHUP() { return get_static_field<"POLLHUP", jint>(); }
	static jint POLLIN() { return get_static_field<"POLLIN", jint>(); }
	static jint POLLNVAL() { return get_static_field<"POLLNVAL", jint>(); }
	static jint POLLOUT() { return get_static_field<"POLLOUT", jint>(); }
	static jint POLLPRI() { return get_static_field<"POLLPRI", jint>(); }
	static jint POLLRDBAND() { return get_static_field<"POLLRDBAND", jint>(); }
	static jint POLLRDNORM() { return get_static_field<"POLLRDNORM", jint>(); }
	static jint POLLWRBAND() { return get_static_field<"POLLWRBAND", jint>(); }
	static jint POLLWRNORM() { return get_static_field<"POLLWRNORM", jint>(); }
	static jint PROT_EXEC() { return get_static_field<"PROT_EXEC", jint>(); }
	static jint PROT_NONE() { return get_static_field<"PROT_NONE", jint>(); }
	static jint PROT_READ() { return get_static_field<"PROT_READ", jint>(); }
	static jint PROT_WRITE() { return get_static_field<"PROT_WRITE", jint>(); }
	static jint PR_GET_DUMPABLE() { return get_static_field<"PR_GET_DUMPABLE", jint>(); }
	static jint PR_SET_DUMPABLE() { return get_static_field<"PR_SET_DUMPABLE", jint>(); }
	static jint PR_SET_NO_NEW_PRIVS() { return get_static_field<"PR_SET_NO_NEW_PRIVS", jint>(); }
	static jint RTMGRP_NEIGH() { return get_static_field<"RTMGRP_NEIGH", jint>(); }
	static jint RT_SCOPE_HOST() { return get_static_field<"RT_SCOPE_HOST", jint>(); }
	static jint RT_SCOPE_LINK() { return get_static_field<"RT_SCOPE_LINK", jint>(); }
	static jint RT_SCOPE_NOWHERE() { return get_static_field<"RT_SCOPE_NOWHERE", jint>(); }
	static jint RT_SCOPE_SITE() { return get_static_field<"RT_SCOPE_SITE", jint>(); }
	static jint RT_SCOPE_UNIVERSE() { return get_static_field<"RT_SCOPE_UNIVERSE", jint>(); }
	static jint R_OK() { return get_static_field<"R_OK", jint>(); }
	static jint SEEK_CUR() { return get_static_field<"SEEK_CUR", jint>(); }
	static jint SEEK_END() { return get_static_field<"SEEK_END", jint>(); }
	static jint SEEK_SET() { return get_static_field<"SEEK_SET", jint>(); }
	static jint SHUT_RD() { return get_static_field<"SHUT_RD", jint>(); }
	static jint SHUT_RDWR() { return get_static_field<"SHUT_RDWR", jint>(); }
	static jint SHUT_WR() { return get_static_field<"SHUT_WR", jint>(); }
	static jint SIGABRT() { return get_static_field<"SIGABRT", jint>(); }
	static jint SIGALRM() { return get_static_field<"SIGALRM", jint>(); }
	static jint SIGBUS() { return get_static_field<"SIGBUS", jint>(); }
	static jint SIGCHLD() { return get_static_field<"SIGCHLD", jint>(); }
	static jint SIGCONT() { return get_static_field<"SIGCONT", jint>(); }
	static jint SIGFPE() { return get_static_field<"SIGFPE", jint>(); }
	static jint SIGHUP() { return get_static_field<"SIGHUP", jint>(); }
	static jint SIGILL() { return get_static_field<"SIGILL", jint>(); }
	static jint SIGINT() { return get_static_field<"SIGINT", jint>(); }
	static jint SIGIO() { return get_static_field<"SIGIO", jint>(); }
	static jint SIGKILL() { return get_static_field<"SIGKILL", jint>(); }
	static jint SIGPIPE() { return get_static_field<"SIGPIPE", jint>(); }
	static jint SIGPROF() { return get_static_field<"SIGPROF", jint>(); }
	static jint SIGPWR() { return get_static_field<"SIGPWR", jint>(); }
	static jint SIGQUIT() { return get_static_field<"SIGQUIT", jint>(); }
	static jint SIGRTMAX() { return get_static_field<"SIGRTMAX", jint>(); }
	static jint SIGRTMIN() { return get_static_field<"SIGRTMIN", jint>(); }
	static jint SIGSEGV() { return get_static_field<"SIGSEGV", jint>(); }
	static jint SIGSTKFLT() { return get_static_field<"SIGSTKFLT", jint>(); }
	static jint SIGSTOP() { return get_static_field<"SIGSTOP", jint>(); }
	static jint SIGSYS() { return get_static_field<"SIGSYS", jint>(); }
	static jint SIGTERM() { return get_static_field<"SIGTERM", jint>(); }
	static jint SIGTRAP() { return get_static_field<"SIGTRAP", jint>(); }
	static jint SIGTSTP() { return get_static_field<"SIGTSTP", jint>(); }
	static jint SIGTTIN() { return get_static_field<"SIGTTIN", jint>(); }
	static jint SIGTTOU() { return get_static_field<"SIGTTOU", jint>(); }
	static jint SIGURG() { return get_static_field<"SIGURG", jint>(); }
	static jint SIGUSR1() { return get_static_field<"SIGUSR1", jint>(); }
	static jint SIGUSR2() { return get_static_field<"SIGUSR2", jint>(); }
	static jint SIGVTALRM() { return get_static_field<"SIGVTALRM", jint>(); }
	static jint SIGWINCH() { return get_static_field<"SIGWINCH", jint>(); }
	static jint SIGXCPU() { return get_static_field<"SIGXCPU", jint>(); }
	static jint SIGXFSZ() { return get_static_field<"SIGXFSZ", jint>(); }
	static jint SIOCGIFADDR() { return get_static_field<"SIOCGIFADDR", jint>(); }
	static jint SIOCGIFBRDADDR() { return get_static_field<"SIOCGIFBRDADDR", jint>(); }
	static jint SIOCGIFDSTADDR() { return get_static_field<"SIOCGIFDSTADDR", jint>(); }
	static jint SIOCGIFNETMASK() { return get_static_field<"SIOCGIFNETMASK", jint>(); }
	static jint SOCK_CLOEXEC() { return get_static_field<"SOCK_CLOEXEC", jint>(); }
	static jint SOCK_DGRAM() { return get_static_field<"SOCK_DGRAM", jint>(); }
	static jint SOCK_NONBLOCK() { return get_static_field<"SOCK_NONBLOCK", jint>(); }
	static jint SOCK_RAW() { return get_static_field<"SOCK_RAW", jint>(); }
	static jint SOCK_SEQPACKET() { return get_static_field<"SOCK_SEQPACKET", jint>(); }
	static jint SOCK_STREAM() { return get_static_field<"SOCK_STREAM", jint>(); }
	static jint SOL_SOCKET() { return get_static_field<"SOL_SOCKET", jint>(); }
	static jint SO_BINDTODEVICE() { return get_static_field<"SO_BINDTODEVICE", jint>(); }
	static jint SO_BROADCAST() { return get_static_field<"SO_BROADCAST", jint>(); }
	static jint SO_DEBUG() { return get_static_field<"SO_DEBUG", jint>(); }
	static jint SO_DONTROUTE() { return get_static_field<"SO_DONTROUTE", jint>(); }
	static jint SO_ERROR() { return get_static_field<"SO_ERROR", jint>(); }
	static jint SO_KEEPALIVE() { return get_static_field<"SO_KEEPALIVE", jint>(); }
	static jint SO_LINGER() { return get_static_field<"SO_LINGER", jint>(); }
	static jint SO_OOBINLINE() { return get_static_field<"SO_OOBINLINE", jint>(); }
	static jint SO_PASSCRED() { return get_static_field<"SO_PASSCRED", jint>(); }
	static jint SO_PEERCRED() { return get_static_field<"SO_PEERCRED", jint>(); }
	static jint SO_RCVBUF() { return get_static_field<"SO_RCVBUF", jint>(); }
	static jint SO_RCVLOWAT() { return get_static_field<"SO_RCVLOWAT", jint>(); }
	static jint SO_RCVTIMEO() { return get_static_field<"SO_RCVTIMEO", jint>(); }
	static jint SO_REUSEADDR() { return get_static_field<"SO_REUSEADDR", jint>(); }
	static jint SO_SNDBUF() { return get_static_field<"SO_SNDBUF", jint>(); }
	static jint SO_SNDLOWAT() { return get_static_field<"SO_SNDLOWAT", jint>(); }
	static jint SO_SNDTIMEO() { return get_static_field<"SO_SNDTIMEO", jint>(); }
	static jint SO_TYPE() { return get_static_field<"SO_TYPE", jint>(); }
	static jint STDERR_FILENO() { return get_static_field<"STDERR_FILENO", jint>(); }
	static jint STDIN_FILENO() { return get_static_field<"STDIN_FILENO", jint>(); }
	static jint STDOUT_FILENO() { return get_static_field<"STDOUT_FILENO", jint>(); }
	static jint ST_MANDLOCK() { return get_static_field<"ST_MANDLOCK", jint>(); }
	static jint ST_NOATIME() { return get_static_field<"ST_NOATIME", jint>(); }
	static jint ST_NODEV() { return get_static_field<"ST_NODEV", jint>(); }
	static jint ST_NODIRATIME() { return get_static_field<"ST_NODIRATIME", jint>(); }
	static jint ST_NOEXEC() { return get_static_field<"ST_NOEXEC", jint>(); }
	static jint ST_NOSUID() { return get_static_field<"ST_NOSUID", jint>(); }
	static jint ST_RDONLY() { return get_static_field<"ST_RDONLY", jint>(); }
	static jint ST_RELATIME() { return get_static_field<"ST_RELATIME", jint>(); }
	static jint ST_SYNCHRONOUS() { return get_static_field<"ST_SYNCHRONOUS", jint>(); }
	static jint S_IFBLK() { return get_static_field<"S_IFBLK", jint>(); }
	static jint S_IFCHR() { return get_static_field<"S_IFCHR", jint>(); }
	static jint S_IFDIR() { return get_static_field<"S_IFDIR", jint>(); }
	static jint S_IFIFO() { return get_static_field<"S_IFIFO", jint>(); }
	static jint S_IFLNK() { return get_static_field<"S_IFLNK", jint>(); }
	static jint S_IFMT() { return get_static_field<"S_IFMT", jint>(); }
	static jint S_IFREG() { return get_static_field<"S_IFREG", jint>(); }
	static jint S_IFSOCK() { return get_static_field<"S_IFSOCK", jint>(); }
	static jint S_IRGRP() { return get_static_field<"S_IRGRP", jint>(); }
	static jint S_IROTH() { return get_static_field<"S_IROTH", jint>(); }
	static jint S_IRUSR() { return get_static_field<"S_IRUSR", jint>(); }
	static jint S_IRWXG() { return get_static_field<"S_IRWXG", jint>(); }
	static jint S_IRWXO() { return get_static_field<"S_IRWXO", jint>(); }
	static jint S_IRWXU() { return get_static_field<"S_IRWXU", jint>(); }
	static jint S_ISGID() { return get_static_field<"S_ISGID", jint>(); }
	static jint S_ISUID() { return get_static_field<"S_ISUID", jint>(); }
	static jint S_ISVTX() { return get_static_field<"S_ISVTX", jint>(); }
	static jint S_IWGRP() { return get_static_field<"S_IWGRP", jint>(); }
	static jint S_IWOTH() { return get_static_field<"S_IWOTH", jint>(); }
	static jint S_IWUSR() { return get_static_field<"S_IWUSR", jint>(); }
	static jint S_IXGRP() { return get_static_field<"S_IXGRP", jint>(); }
	static jint S_IXOTH() { return get_static_field<"S_IXOTH", jint>(); }
	static jint S_IXUSR() { return get_static_field<"S_IXUSR", jint>(); }
	static jint TCP_NODELAY() { return get_static_field<"TCP_NODELAY", jint>(); }
	static jint TCP_USER_TIMEOUT() { return get_static_field<"TCP_USER_TIMEOUT", jint>(); }
	static jint WCONTINUED() { return get_static_field<"WCONTINUED", jint>(); }
	static jint WEXITED() { return get_static_field<"WEXITED", jint>(); }
	static jint WNOHANG() { return get_static_field<"WNOHANG", jint>(); }
	static jint WNOWAIT() { return get_static_field<"WNOWAIT", jint>(); }
	static jint WSTOPPED() { return get_static_field<"WSTOPPED", jint>(); }
	static jint WUNTRACED() { return get_static_field<"WUNTRACED", jint>(); }
	static jint W_OK() { return get_static_field<"W_OK", jint>(); }
	static jint X_OK() { return get_static_field<"X_OK", jint>(); }
	static jint _SC_2_CHAR_TERM() { return get_static_field<"_SC_2_CHAR_TERM", jint>(); }
	static jint _SC_2_C_BIND() { return get_static_field<"_SC_2_C_BIND", jint>(); }
	static jint _SC_2_C_DEV() { return get_static_field<"_SC_2_C_DEV", jint>(); }
	static jint _SC_2_C_VERSION() { return get_static_field<"_SC_2_C_VERSION", jint>(); }
	static jint _SC_2_FORT_DEV() { return get_static_field<"_SC_2_FORT_DEV", jint>(); }
	static jint _SC_2_FORT_RUN() { return get_static_field<"_SC_2_FORT_RUN", jint>(); }
	static jint _SC_2_LOCALEDEF() { return get_static_field<"_SC_2_LOCALEDEF", jint>(); }
	static jint _SC_2_SW_DEV() { return get_static_field<"_SC_2_SW_DEV", jint>(); }
	static jint _SC_2_UPE() { return get_static_field<"_SC_2_UPE", jint>(); }
	static jint _SC_2_VERSION() { return get_static_field<"_SC_2_VERSION", jint>(); }
	static jint _SC_AIO_LISTIO_MAX() { return get_static_field<"_SC_AIO_LISTIO_MAX", jint>(); }
	static jint _SC_AIO_MAX() { return get_static_field<"_SC_AIO_MAX", jint>(); }
	static jint _SC_AIO_PRIO_DELTA_MAX() { return get_static_field<"_SC_AIO_PRIO_DELTA_MAX", jint>(); }
	static jint _SC_ARG_MAX() { return get_static_field<"_SC_ARG_MAX", jint>(); }
	static jint _SC_ASYNCHRONOUS_IO() { return get_static_field<"_SC_ASYNCHRONOUS_IO", jint>(); }
	static jint _SC_ATEXIT_MAX() { return get_static_field<"_SC_ATEXIT_MAX", jint>(); }
	static jint _SC_AVPHYS_PAGES() { return get_static_field<"_SC_AVPHYS_PAGES", jint>(); }
	static jint _SC_BC_BASE_MAX() { return get_static_field<"_SC_BC_BASE_MAX", jint>(); }
	static jint _SC_BC_DIM_MAX() { return get_static_field<"_SC_BC_DIM_MAX", jint>(); }
	static jint _SC_BC_SCALE_MAX() { return get_static_field<"_SC_BC_SCALE_MAX", jint>(); }
	static jint _SC_BC_STRING_MAX() { return get_static_field<"_SC_BC_STRING_MAX", jint>(); }
	static jint _SC_CHILD_MAX() { return get_static_field<"_SC_CHILD_MAX", jint>(); }
	static jint _SC_CLK_TCK() { return get_static_field<"_SC_CLK_TCK", jint>(); }
	static jint _SC_COLL_WEIGHTS_MAX() { return get_static_field<"_SC_COLL_WEIGHTS_MAX", jint>(); }
	static jint _SC_DELAYTIMER_MAX() { return get_static_field<"_SC_DELAYTIMER_MAX", jint>(); }
	static jint _SC_EXPR_NEST_MAX() { return get_static_field<"_SC_EXPR_NEST_MAX", jint>(); }
	static jint _SC_FSYNC() { return get_static_field<"_SC_FSYNC", jint>(); }
	static jint _SC_GETGR_R_SIZE_MAX() { return get_static_field<"_SC_GETGR_R_SIZE_MAX", jint>(); }
	static jint _SC_GETPW_R_SIZE_MAX() { return get_static_field<"_SC_GETPW_R_SIZE_MAX", jint>(); }
	static jint _SC_IOV_MAX() { return get_static_field<"_SC_IOV_MAX", jint>(); }
	static jint _SC_JOB_CONTROL() { return get_static_field<"_SC_JOB_CONTROL", jint>(); }
	static jint _SC_LINE_MAX() { return get_static_field<"_SC_LINE_MAX", jint>(); }
	static jint _SC_LOGIN_NAME_MAX() { return get_static_field<"_SC_LOGIN_NAME_MAX", jint>(); }
	static jint _SC_MAPPED_FILES() { return get_static_field<"_SC_MAPPED_FILES", jint>(); }
	static jint _SC_MEMLOCK() { return get_static_field<"_SC_MEMLOCK", jint>(); }
	static jint _SC_MEMLOCK_RANGE() { return get_static_field<"_SC_MEMLOCK_RANGE", jint>(); }
	static jint _SC_MEMORY_PROTECTION() { return get_static_field<"_SC_MEMORY_PROTECTION", jint>(); }
	static jint _SC_MESSAGE_PASSING() { return get_static_field<"_SC_MESSAGE_PASSING", jint>(); }
	static jint _SC_MQ_OPEN_MAX() { return get_static_field<"_SC_MQ_OPEN_MAX", jint>(); }
	static jint _SC_MQ_PRIO_MAX() { return get_static_field<"_SC_MQ_PRIO_MAX", jint>(); }
	static jint _SC_NGROUPS_MAX() { return get_static_field<"_SC_NGROUPS_MAX", jint>(); }
	static jint _SC_NPROCESSORS_CONF() { return get_static_field<"_SC_NPROCESSORS_CONF", jint>(); }
	static jint _SC_NPROCESSORS_ONLN() { return get_static_field<"_SC_NPROCESSORS_ONLN", jint>(); }
	static jint _SC_OPEN_MAX() { return get_static_field<"_SC_OPEN_MAX", jint>(); }
	static jint _SC_PAGESIZE() { return get_static_field<"_SC_PAGESIZE", jint>(); }
	static jint _SC_PAGE_SIZE() { return get_static_field<"_SC_PAGE_SIZE", jint>(); }
	static jint _SC_PASS_MAX() { return get_static_field<"_SC_PASS_MAX", jint>(); }
	static jint _SC_PHYS_PAGES() { return get_static_field<"_SC_PHYS_PAGES", jint>(); }
	static jint _SC_PRIORITIZED_IO() { return get_static_field<"_SC_PRIORITIZED_IO", jint>(); }
	static jint _SC_PRIORITY_SCHEDULING() { return get_static_field<"_SC_PRIORITY_SCHEDULING", jint>(); }
	static jint _SC_REALTIME_SIGNALS() { return get_static_field<"_SC_REALTIME_SIGNALS", jint>(); }
	static jint _SC_RE_DUP_MAX() { return get_static_field<"_SC_RE_DUP_MAX", jint>(); }
	static jint _SC_RTSIG_MAX() { return get_static_field<"_SC_RTSIG_MAX", jint>(); }
	static jint _SC_SAVED_IDS() { return get_static_field<"_SC_SAVED_IDS", jint>(); }
	static jint _SC_SEMAPHORES() { return get_static_field<"_SC_SEMAPHORES", jint>(); }
	static jint _SC_SEM_NSEMS_MAX() { return get_static_field<"_SC_SEM_NSEMS_MAX", jint>(); }
	static jint _SC_SEM_VALUE_MAX() { return get_static_field<"_SC_SEM_VALUE_MAX", jint>(); }
	static jint _SC_SHARED_MEMORY_OBJECTS() { return get_static_field<"_SC_SHARED_MEMORY_OBJECTS", jint>(); }
	static jint _SC_SIGQUEUE_MAX() { return get_static_field<"_SC_SIGQUEUE_MAX", jint>(); }
	static jint _SC_STREAM_MAX() { return get_static_field<"_SC_STREAM_MAX", jint>(); }
	static jint _SC_SYNCHRONIZED_IO() { return get_static_field<"_SC_SYNCHRONIZED_IO", jint>(); }
	static jint _SC_THREADS() { return get_static_field<"_SC_THREADS", jint>(); }
	static jint _SC_THREAD_ATTR_STACKADDR() { return get_static_field<"_SC_THREAD_ATTR_STACKADDR", jint>(); }
	static jint _SC_THREAD_ATTR_STACKSIZE() { return get_static_field<"_SC_THREAD_ATTR_STACKSIZE", jint>(); }
	static jint _SC_THREAD_DESTRUCTOR_ITERATIONS() { return get_static_field<"_SC_THREAD_DESTRUCTOR_ITERATIONS", jint>(); }
	static jint _SC_THREAD_KEYS_MAX() { return get_static_field<"_SC_THREAD_KEYS_MAX", jint>(); }
	static jint _SC_THREAD_PRIORITY_SCHEDULING() { return get_static_field<"_SC_THREAD_PRIORITY_SCHEDULING", jint>(); }
	static jint _SC_THREAD_PRIO_INHERIT() { return get_static_field<"_SC_THREAD_PRIO_INHERIT", jint>(); }
	static jint _SC_THREAD_PRIO_PROTECT() { return get_static_field<"_SC_THREAD_PRIO_PROTECT", jint>(); }
	static jint _SC_THREAD_SAFE_FUNCTIONS() { return get_static_field<"_SC_THREAD_SAFE_FUNCTIONS", jint>(); }
	static jint _SC_THREAD_STACK_MIN() { return get_static_field<"_SC_THREAD_STACK_MIN", jint>(); }
	static jint _SC_THREAD_THREADS_MAX() { return get_static_field<"_SC_THREAD_THREADS_MAX", jint>(); }
	static jint _SC_TIMERS() { return get_static_field<"_SC_TIMERS", jint>(); }
	static jint _SC_TIMER_MAX() { return get_static_field<"_SC_TIMER_MAX", jint>(); }
	static jint _SC_TTY_NAME_MAX() { return get_static_field<"_SC_TTY_NAME_MAX", jint>(); }
	static jint _SC_TZNAME_MAX() { return get_static_field<"_SC_TZNAME_MAX", jint>(); }
	static jint _SC_VERSION() { return get_static_field<"_SC_VERSION", jint>(); }
	static jint _SC_XBS5_ILP32_OFF32() { return get_static_field<"_SC_XBS5_ILP32_OFF32", jint>(); }
	static jint _SC_XBS5_ILP32_OFFBIG() { return get_static_field<"_SC_XBS5_ILP32_OFFBIG", jint>(); }
	static jint _SC_XBS5_LP64_OFF64() { return get_static_field<"_SC_XBS5_LP64_OFF64", jint>(); }
	static jint _SC_XBS5_LPBIG_OFFBIG() { return get_static_field<"_SC_XBS5_LPBIG_OFFBIG", jint>(); }
	static jint _SC_XOPEN_CRYPT() { return get_static_field<"_SC_XOPEN_CRYPT", jint>(); }
	static jint _SC_XOPEN_ENH_I18N() { return get_static_field<"_SC_XOPEN_ENH_I18N", jint>(); }
	static jint _SC_XOPEN_LEGACY() { return get_static_field<"_SC_XOPEN_LEGACY", jint>(); }
	static jint _SC_XOPEN_REALTIME() { return get_static_field<"_SC_XOPEN_REALTIME", jint>(); }
	static jint _SC_XOPEN_REALTIME_THREADS() { return get_static_field<"_SC_XOPEN_REALTIME_THREADS", jint>(); }
	static jint _SC_XOPEN_SHM() { return get_static_field<"_SC_XOPEN_SHM", jint>(); }
	static jint _SC_XOPEN_UNIX() { return get_static_field<"_SC_XOPEN_UNIX", jint>(); }
	static jint _SC_XOPEN_VERSION() { return get_static_field<"_SC_XOPEN_VERSION", jint>(); }
	static jint _SC_XOPEN_XCU_VERSION() { return get_static_field<"_SC_XOPEN_XCU_VERSION", jint>(); }

	static jboolean S_ISBLK(jint mode) { return call_static_method<"S_ISBLK", jboolean>(mode); }
	static jboolean S_ISCHR(jint mode) { return call_static_method<"S_ISCHR", jboolean>(mode); }
	static jboolean S_ISDIR(jint mode) { return call_static_method<"S_ISDIR", jboolean>(mode); }
	static jboolean S_ISFIFO(jint mode) { return call_static_method<"S_ISFIFO", jboolean>(mode); }
	static jboolean S_ISREG(jint mode) { return call_static_method<"S_ISREG", jboolean>(mode); }
	static jboolean S_ISLNK(jint mode) { return call_static_method<"S_ISLNK", jboolean>(mode); }
	static jboolean S_ISSOCK(jint mode) { return call_static_method<"S_ISSOCK", jboolean>(mode); }
	static jint WEXITSTATUS(jint status) { return call_static_method<"WEXITSTATUS", jint>(status); }
	static jboolean WCOREDUMP(jint status) { return call_static_method<"WCOREDUMP", jboolean>(status); }
	static jint WTERMSIG(jint status) { return call_static_method<"WTERMSIG", jint>(status); }
	static jint WSTOPSIG(jint status) { return call_static_method<"WSTOPSIG", jint>(status); }
	static jboolean WIFEXITED(jint status) { return call_static_method<"WIFEXITED", jboolean>(status); }
	static jboolean WIFSTOPPED(jint status) { return call_static_method<"WIFSTOPPED", jboolean>(status); }
	static jboolean WIFSIGNALED(jint status) { return call_static_method<"WIFSIGNALED", jboolean>(status); }
	static jni::ref<java::lang::String> gaiName(jint error) { return call_static_method<"gaiName", jni::ref<java::lang::String>>(error); }
	static jni::ref<java::lang::String> errnoName(jint errno) { return call_static_method<"errnoName", jni::ref<java::lang::String>>(errno); }

protected:

	OsConstants(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_SYSTEM_OSCONSTANTS
