// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/os/Parcelable.h>

#ifndef SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO_FWD
#define SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::app { class ActivityManager_RecentTaskInfo; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::app::ActivityManager_RecentTaskInfo>
{
	static constexpr fixed_string class_name = "android/app/ActivityManager$RecentTaskInfo";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::android::os::Parcelable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO)
#define SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/app/ActivityManager_TaskDescription.h>
#include <scapix/java_api/android/content/ComponentName.h>
#include <scapix/java_api/android/content/Intent.h>
#include <scapix/java_api/android/os/Parcel.h>
#include <scapix/java_api/android/os/Parcelable_Creator.h>
#include <scapix/java_api/java/lang/CharSequence.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::app::ActivityManager_RecentTaskInfo : public jni::object_base<"android/app/ActivityManager$RecentTaskInfo",
	java::lang::Object,
	android::os::Parcelable>
{
public:

	static jni::ref<android::os::Parcelable_Creator> CREATOR() { return get_static_field<"CREATOR", jni::ref<android::os::Parcelable_Creator>>(); }
	jint affiliatedTaskId() { return get_field<"affiliatedTaskId", jint>(); }
	void affiliatedTaskId(jint v) { set_field<"affiliatedTaskId", jint>(v); }
	jni::ref<android::content::ComponentName> baseActivity() { return get_field<"baseActivity", jni::ref<android::content::ComponentName>>(); }
	void baseActivity(jni::ref<android::content::ComponentName> v) { set_field<"baseActivity", jni::ref<android::content::ComponentName>>(v); }
	jni::ref<android::content::Intent> baseIntent() { return get_field<"baseIntent", jni::ref<android::content::Intent>>(); }
	void baseIntent(jni::ref<android::content::Intent> v) { set_field<"baseIntent", jni::ref<android::content::Intent>>(v); }
	jni::ref<java::lang::CharSequence> description() { return get_field<"description", jni::ref<java::lang::CharSequence>>(); }
	void description(jni::ref<java::lang::CharSequence> v) { set_field<"description", jni::ref<java::lang::CharSequence>>(v); }
	jint id() { return get_field<"id", jint>(); }
	void id(jint v) { set_field<"id", jint>(v); }
	jint numActivities() { return get_field<"numActivities", jint>(); }
	void numActivities(jint v) { set_field<"numActivities", jint>(v); }
	jni::ref<android::content::ComponentName> origActivity() { return get_field<"origActivity", jni::ref<android::content::ComponentName>>(); }
	void origActivity(jni::ref<android::content::ComponentName> v) { set_field<"origActivity", jni::ref<android::content::ComponentName>>(v); }
	jint persistentId() { return get_field<"persistentId", jint>(); }
	void persistentId(jint v) { set_field<"persistentId", jint>(v); }
	jni::ref<android::app::ActivityManager_TaskDescription> taskDescription() { return get_field<"taskDescription", jni::ref<android::app::ActivityManager_TaskDescription>>(); }
	void taskDescription(jni::ref<android::app::ActivityManager_TaskDescription> v) { set_field<"taskDescription", jni::ref<android::app::ActivityManager_TaskDescription>>(v); }
	jni::ref<android::content::ComponentName> topActivity() { return get_field<"topActivity", jni::ref<android::content::ComponentName>>(); }
	void topActivity(jni::ref<android::content::ComponentName> v) { set_field<"topActivity", jni::ref<android::content::ComponentName>>(v); }

	static jni::ref<android::app::ActivityManager_RecentTaskInfo> new_object() { return base_::new_object(); }
	jint describeContents() { return call_method<"describeContents", jint>(); }
	void writeToParcel(jni::ref<android::os::Parcel> dest, jint flags) { return call_method<"writeToParcel", void>(dest, flags); }
	void readFromParcel(jni::ref<android::os::Parcel> source) { return call_method<"readFromParcel", void>(source); }

protected:

	ActivityManager_RecentTaskInfo(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_APP_ACTIVITYMANAGER_RECENTTASKINFO
