// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/javax/swing/text/html/BlockView.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::swing::text::html { class ListView; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::text::html::ListView>
{
	static constexpr fixed_string class_name = "javax/swing/text/html/ListView";
	using base_classes = std::tuple<scapix::java_api::javax::swing::text::html::BlockView>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW)
#define SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/awt/Graphics.h>
#include <scapix/java_api/java/awt/Shape.h>
#include <scapix/java_api/javax/swing/text/Element.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::swing::text::html::ListView : public jni::object_base<"javax/swing/text/html/ListView",
	javax::swing::text::html::BlockView>
{
public:

	static jni::ref<javax::swing::text::html::ListView> new_object(jni::ref<javax::swing::text::Element> p1) { return base_::new_object(p1); }
	jfloat getAlignment(jint p1) { return call_method<"getAlignment", jfloat>(p1); }
	void paint(jni::ref<java::awt::Graphics> p1, jni::ref<java::awt::Shape> p2) { return call_method<"paint", void>(p1, p2); }

protected:

	ListView(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_LISTVIEW
