// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/javax/swing/text/html/Map_RegionContainment.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::swing::text::html { class Map_DefaultRegionContainment; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::text::html::Map_DefaultRegionContainment>
{
	static constexpr fixed_string class_name = "javax/swing/text/html/Map$DefaultRegionContainment";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::javax::swing::text::html::Map_RegionContainment>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT)
#define SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class javax::swing::text::html::Map_DefaultRegionContainment : public jni::object_base<"javax/swing/text/html/Map$DefaultRegionContainment",
	java::lang::Object,
	javax::swing::text::html::Map_RegionContainment>
{
public:

	static jni::ref<javax::swing::text::html::Map_DefaultRegionContainment> sharedInstance() { return call_static_method<"sharedInstance", jni::ref<javax::swing::text::html::Map_DefaultRegionContainment>>(); }
	jboolean contains(jint p1, jint p2, jint p3, jint p4) { return call_method<"contains", jboolean>(p1, p2, p3, p4); }

protected:

	Map_DefaultRegionContainment(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TEXT_HTML_MAP_DEFAULTREGIONCONTAINMENT
