// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/javax/lang/model/util/SimpleTypeVisitor8.h>

#ifndef SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9_FWD
#define SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace javax::lang::model::util {

class SimpleTypeVisitor9;

} // namespace javax::lang::model::util
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::lang::model::util::SimpleTypeVisitor9>
{
	static constexpr fixed_string class_name = "javax/lang/model/util/SimpleTypeVisitor9";
	using base_classes = std::tuple<scapix::java_api::javax::lang::model::util::SimpleTypeVisitor8>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9
#define SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::lang::model::util::SimpleTypeVisitor9 : public jni::object_base<"javax/lang/model/util/SimpleTypeVisitor9",
	javax::lang::model::util::SimpleTypeVisitor8>
{
public:
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_LANG_MODEL_UTIL_SIMPLETYPEVISITOR9
#endif // SCAPIX_JAVA_API_FWD
