// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/provider/BaseColumns.h>

#ifndef SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART_FWD
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::provider { class Telephony_Mms_Part; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::provider::Telephony_Mms_Part>
{
	static constexpr fixed_string class_name = "android/provider/Telephony$Mms$Part";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::android::provider::BaseColumns>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART)
#define SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::provider::Telephony_Mms_Part : public jni::object_base<"android/provider/Telephony$Mms$Part",
	java::lang::Object,
	android::provider::BaseColumns>
{
public:

	static jni::ref<java::lang::String> CHARSET() { return get_static_field<"CHARSET", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CONTENT_DISPOSITION() { return get_static_field<"CONTENT_DISPOSITION", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CONTENT_ID() { return get_static_field<"CONTENT_ID", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CONTENT_LOCATION() { return get_static_field<"CONTENT_LOCATION", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CONTENT_TYPE() { return get_static_field<"CONTENT_TYPE", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CT_START() { return get_static_field<"CT_START", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> CT_TYPE() { return get_static_field<"CT_TYPE", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> FILENAME() { return get_static_field<"FILENAME", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> MSG_ID() { return get_static_field<"MSG_ID", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> NAME() { return get_static_field<"NAME", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> SEQ() { return get_static_field<"SEQ", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> TEXT() { return get_static_field<"TEXT", jni::ref<java::lang::String>>(); }
	static jni::ref<java::lang::String> _DATA() { return get_static_field<"_DATA", jni::ref<java::lang::String>>(); }


protected:

	Telephony_Mms_Part(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_PROVIDER_TELEPHONY_MMS_PART
