// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/beans/PersistenceDelegate.h>

#ifndef SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE_FWD
#define SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::beans { class MetaData_java_lang_String_PersistenceDelegate; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::beans::MetaData_java_lang_String_PersistenceDelegate>
{
	static constexpr fixed_string class_name = "java/beans/MetaData$java_lang_String_PersistenceDelegate";
	using base_classes = std::tuple<scapix::java_api::java::beans::PersistenceDelegate>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE)
#define SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/beans/Encoder.h>
#include <scapix/java_api/java/lang/Object.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class java::beans::MetaData_java_lang_String_PersistenceDelegate : public jni::object_base<"java/beans/MetaData$java_lang_String_PersistenceDelegate",
	java::beans::PersistenceDelegate>
{
public:

	void writeObject(jni::ref<java::lang::Object> p1, jni::ref<java::beans::Encoder> p2) { return call_method<"writeObject", void>(p1, p2); }

protected:

	MetaData_java_lang_String_PersistenceDelegate(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_BEANS_METADATA_JAVA_LANG_STRING_PERSISTENCEDELEGATE
