// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER_FWD
#define SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::jdk::internal::module { class ModuleHashes_Builder; }

template<>
struct scapix::jni::object_traits<scapix::java_api::jdk::internal::module::ModuleHashes_Builder>
{
	static constexpr fixed_string class_name = "jdk/internal/module/ModuleHashes$Builder";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER)
#define SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/jdk/internal/module/ModuleHashes.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class jdk::internal::module::ModuleHashes_Builder : public jni::object_base<"jdk/internal/module/ModuleHashes$Builder",
	java::lang::Object>
{
public:

	jni::ref<jdk::internal::module::ModuleHashes_Builder> hashForModule(jni::ref<java::lang::String> mn, jni::ref<jni::array<jbyte>> hash) { return call_method<"hashForModule", jni::ref<jdk::internal::module::ModuleHashes_Builder>>(mn, hash); }
	jni::ref<jdk::internal::module::ModuleHashes> build() { return call_method<"build", jni::ref<jdk::internal::module::ModuleHashes>>(); }

protected:

	ModuleHashes_Builder(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_INTERNAL_MODULE_MODULEHASHES_BUILDER
