// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/io/Reader.h>

#ifndef SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER_FWD
#define SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::io { class CharArrayReader; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::io::CharArrayReader>
{
	static constexpr fixed_string class_name = "java/io/CharArrayReader";
	using base_classes = std::tuple<scapix::java_api::java::io::Reader>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER)
#define SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::io::CharArrayReader : public jni::object_base<"java/io/CharArrayReader",
	java::io::Reader>
{
public:

	static jni::ref<java::io::CharArrayReader> new_object(jni::ref<jni::array<jchar>> buf) { return base_::new_object(buf); }
	static jni::ref<java::io::CharArrayReader> new_object(jni::ref<jni::array<jchar>> buf, jint offset, jint length) { return base_::new_object(buf, offset, length); }
	jint read() { return call_method<"read", jint>(); }
	jint read(jni::ref<jni::array<jchar>> b, jint off, jint len) { return call_method<"read", jint>(b, off, len); }
	jlong skip(jlong n) { return call_method<"skip", jlong>(n); }
	jboolean ready() { return call_method<"ready", jboolean>(); }
	jboolean markSupported() { return call_method<"markSupported", jboolean>(); }
	void mark(jint readAheadLimit) { return call_method<"mark", void>(readAheadLimit); }
	void reset() { return call_method<"reset", void>(); }
	void close() { return call_method<"close", void>(); }

protected:

	CharArrayReader(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_IO_CHARARRAYREADER
