// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/io/Writer.h>

#ifndef SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER_FWD
#define SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::io { class CharArrayWriter; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::io::CharArrayWriter>
{
	static constexpr fixed_string class_name = "java/io/CharArrayWriter";
	using base_classes = std::tuple<scapix::java_api::java::io::Writer>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER)
#define SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/CharSequence.h>
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::io::CharArrayWriter : public jni::object_base<"java/io/CharArrayWriter",
	java::io::Writer>
{
public:

	static jni::ref<java::io::CharArrayWriter> new_object() { return base_::new_object(); }
	static jni::ref<java::io::CharArrayWriter> new_object(jint initialSize) { return base_::new_object(initialSize); }
	void close() { return call_method<"close", void>(); }
	void flush() { return call_method<"flush", void>(); }
	void reset() { return call_method<"reset", void>(); }
	jint size() { return call_method<"size", jint>(); }
	jni::ref<jni::array<jchar>> toCharArray() { return call_method<"toCharArray", jni::ref<jni::array<jchar>>>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	void write(jni::ref<jni::array<jchar>> buffer, jint offset, jint len) { return call_method<"write", void>(buffer, offset, len); }
	void write(jint oneChar) { return call_method<"write", void>(oneChar); }
	void write(jni::ref<java::lang::String> str, jint offset, jint count) { return call_method<"write", void>(str, offset, count); }
	void writeTo(jni::ref<java::io::Writer> out) { return call_method<"writeTo", void>(out); }
	jni::ref<java::io::CharArrayWriter> append(jchar c) { return call_method<"append", jni::ref<java::io::CharArrayWriter>>(c); }
	jni::ref<java::io::CharArrayWriter> append(jni::ref<java::lang::CharSequence> csq) { return call_method<"append", jni::ref<java::io::CharArrayWriter>>(csq); }
	jni::ref<java::io::CharArrayWriter> append(jni::ref<java::lang::CharSequence> csq, jint start, jint end) { return call_method<"append", jni::ref<java::io::CharArrayWriter>>(csq, start, end); }

protected:

	CharArrayWriter(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_IO_CHARARRAYWRITER
