// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION_FWD
#define SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::audio { class AudioSecurityAction; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::audio::AudioSecurityAction>
{
	static constexpr fixed_string class_name = "sun/audio/AudioSecurityAction";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION)
#define SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::audio::AudioSecurityAction : public jni::object_base<"sun/audio/AudioSecurityAction",
	java::lang::Object>
{
public:

	jni::ref<java::lang::Object> run() { return call_method<"run", jni::ref<java::lang::Object>>(); }

protected:

	AudioSecurityAction(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_AUDIO_AUDIOSECURITYACTION
