// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_FWD
#define SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::view { class View_OnUnhandledKeyEventListener; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::view::View_OnUnhandledKeyEventListener>
{
	static constexpr fixed_string class_name = "android/view/View$OnUnhandledKeyEventListener";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER)
#define SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/view/KeyEvent.h>
#include <scapix/java_api/android/view/View.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::view::View_OnUnhandledKeyEventListener : public jni::object_base<"android/view/View$OnUnhandledKeyEventListener",
	java::lang::Object>
{
public:

	jboolean onUnhandledKeyEvent(jni::ref<android::view::View> p1, jni::ref<android::view::KeyEvent> p2) { return call_method<"onUnhandledKeyEvent", jboolean>(p1, p2); }

protected:

	View_OnUnhandledKeyEventListener(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER
