// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG_FWD
#define SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace com::sun::javadoc {

class Tag;

} // namespace com::sun::javadoc
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::javadoc::Tag>
{
	static constexpr fixed_string class_name = "com/sun/javadoc/Tag";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG
#define SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/com/sun/javadoc/Doc.h>
#include <scapix/java_api/com/sun/javadoc/SourcePosition.h>
#include <scapix/java_api/java/lang/String.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::javadoc::Tag : public jni::object_base<"com/sun/javadoc/Tag",
	java::lang::Object>
{
public:

	jni::ref<java::lang::String> name() { return call_method<"name", jni::ref<java::lang::String>>(); }
	jni::ref<com::sun::javadoc::Doc> holder() { return call_method<"holder", jni::ref<com::sun::javadoc::Doc>>(); }
	jni::ref<java::lang::String> kind() { return call_method<"kind", jni::ref<java::lang::String>>(); }
	jni::ref<java::lang::String> text() { return call_method<"text", jni::ref<java::lang::String>>(); }
	jni::ref<java::lang::String> toString() { return call_method<"toString", jni::ref<java::lang::String>>(); }
	jni::ref<jni::array<com::sun::javadoc::Tag>> inlineTags() { return call_method<"inlineTags", jni::ref<jni::array<com::sun::javadoc::Tag>>>(); }
	jni::ref<jni::array<com::sun::javadoc::Tag>> firstSentenceTags() { return call_method<"firstSentenceTags", jni::ref<jni::array<com::sun::javadoc::Tag>>>(); }
	jni::ref<com::sun::javadoc::SourcePosition> position() { return call_method<"position", jni::ref<com::sun::javadoc::SourcePosition>>(); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JAVADOC_TAG
#endif // SCAPIX_JAVA_API_FWD
