// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/sun/security/provider/AbstractHashDrbg.h>

#ifndef SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG_FWD
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::security::provider { class HashDrbg; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::security::provider::HashDrbg>
{
	static constexpr fixed_string class_name = "sun/security/provider/HashDrbg";
	using base_classes = std::tuple<scapix::java_api::sun::security::provider::AbstractHashDrbg>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG)
#define SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/security/MessageDigest.h>
#include <scapix/java_api/java/security/SecureRandomParameters.h>
#include <scapix/java_api/java/util/List.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::security::provider::HashDrbg : public jni::object_base<"sun/security/provider/HashDrbg",
	sun::security::provider::AbstractHashDrbg>
{
public:

	static jni::ref<sun::security::provider::HashDrbg> new_object(jni::ref<java::security::SecureRandomParameters> params) { return base_::new_object(params); }
	static jni::ref<jni::array<jbyte>> hashDf(jni::ref<java::security::MessageDigest> digest, jint outLen, jint requested, jni::ref<java::util::List> inputs) { return call_static_method<"hashDf", jni::ref<jni::array<jbyte>>>(digest, outLen, requested, inputs); }
	void generateAlgorithm(jni::ref<jni::array<jbyte>> result, jni::ref<jni::array<jbyte>> additionalInput) { return call_method<"generateAlgorithm", void>(result, additionalInput); }

protected:

	HashDrbg(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_SECURITY_PROVIDER_HASHDRBG
