// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER_FWD
#define SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::jmx::remote::security { class MBeanServerFileAccessController_Parser; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::jmx::remote::security::MBeanServerFileAccessController_Parser>
{
	static constexpr fixed_string class_name = "com/sun/jmx/remote/security/MBeanServerFileAccessController$Parser";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER)
#define SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class com::sun::jmx::remote::security::MBeanServerFileAccessController_Parser : public jni::object_base<"com/sun/jmx/remote/security/MBeanServerFileAccessController$Parser",
	java::lang::Object>
{
public:


protected:

	MBeanServerFileAccessController_Parser(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_JMX_REMOTE_SECURITY_MBEANSERVERFILEACCESSCONTROLLER_PARSER
