// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/javax/swing/table/TableModel.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace javax::swing::table {

class AbstractTableModel;

} // namespace javax::swing::table
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::table::AbstractTableModel>
{
	static constexpr fixed_string class_name = "javax/swing/table/AbstractTableModel";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::javax::swing::table::TableModel, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL
#define SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/lang/Class.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/EventListener.h>
#include <scapix/java_api/javax/swing/event/TableModelEvent.h>
#include <scapix/java_api/javax/swing/event/TableModelListener.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::swing::table::AbstractTableModel : public jni::object_base<"javax/swing/table/AbstractTableModel",
	java::lang::Object,
	javax::swing::table::TableModel,
	java::io::Serializable>
{
public:

	jni::ref<java::lang::String> getColumnName(jint column) { return call_method<"getColumnName", jni::ref<java::lang::String>>(column); }
	jint findColumn(jni::ref<java::lang::String> columnName) { return call_method<"findColumn", jint>(columnName); }
	jni::ref<java::lang::Class> getColumnClass(jint columnIndex) { return call_method<"getColumnClass", jni::ref<java::lang::Class>>(columnIndex); }
	jboolean isCellEditable(jint rowIndex, jint columnIndex) { return call_method<"isCellEditable", jboolean>(rowIndex, columnIndex); }
	void setValueAt(jni::ref<java::lang::Object> aValue, jint rowIndex, jint columnIndex) { return call_method<"setValueAt", void>(aValue, rowIndex, columnIndex); }
	void addTableModelListener(jni::ref<javax::swing::event::TableModelListener> l) { return call_method<"addTableModelListener", void>(l); }
	void removeTableModelListener(jni::ref<javax::swing::event::TableModelListener> l) { return call_method<"removeTableModelListener", void>(l); }
	jni::ref<jni::array<javax::swing::event::TableModelListener>> getTableModelListeners() { return call_method<"getTableModelListeners", jni::ref<jni::array<javax::swing::event::TableModelListener>>>(); }
	void fireTableDataChanged() { return call_method<"fireTableDataChanged", void>(); }
	void fireTableStructureChanged() { return call_method<"fireTableStructureChanged", void>(); }
	void fireTableRowsInserted(jint firstRow, jint lastRow) { return call_method<"fireTableRowsInserted", void>(firstRow, lastRow); }
	void fireTableRowsUpdated(jint firstRow, jint lastRow) { return call_method<"fireTableRowsUpdated", void>(firstRow, lastRow); }
	void fireTableRowsDeleted(jint firstRow, jint lastRow) { return call_method<"fireTableRowsDeleted", void>(firstRow, lastRow); }
	void fireTableCellUpdated(jint row, jint column) { return call_method<"fireTableCellUpdated", void>(row, column); }
	void fireTableChanged(jni::ref<javax::swing::event::TableModelEvent> e) { return call_method<"fireTableChanged", void>(e); }
	jni::ref<jni::array<java::util::EventListener>> getListeners(jni::ref<java::lang::Class> listenerType) { return call_method<"getListeners", jni::ref<jni::array<java::util::EventListener>>>(listenerType); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_TABLE_ABSTRACTTABLEMODEL
#endif // SCAPIX_JAVA_API_FWD
