// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/android/hardware/camera2/CameraCaptureSession.h>

#ifndef SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION_FWD
#define SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::android::hardware::camera2 { class CameraConstrainedHighSpeedCaptureSession; }

template<>
struct scapix::jni::object_traits<scapix::java_api::android::hardware::camera2::CameraConstrainedHighSpeedCaptureSession>
{
	static constexpr fixed_string class_name = "android/hardware/camera2/CameraConstrainedHighSpeedCaptureSession";
	using base_classes = std::tuple<scapix::java_api::android::hardware::camera2::CameraCaptureSession>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION)
#define SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/hardware/camera2/CaptureRequest.h>
#include <scapix/java_api/java/util/List.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::hardware::camera2::CameraConstrainedHighSpeedCaptureSession : public jni::object_base<"android/hardware/camera2/CameraConstrainedHighSpeedCaptureSession",
	android::hardware::camera2::CameraCaptureSession>
{
public:

	static jni::ref<android::hardware::camera2::CameraConstrainedHighSpeedCaptureSession> new_object() { return base_::new_object(); }
	jni::ref<java::util::List> createHighSpeedRequestList(jni::ref<android::hardware::camera2::CaptureRequest> p1) { return call_method<"createHighSpeedRequestList", jni::ref<java::util::List>>(p1); }

protected:

	CameraConstrainedHighSpeedCaptureSession(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_HARDWARE_CAMERA2_CAMERACONSTRAINEDHIGHSPEEDCAPTURESESSION
