// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/awt/event/MouseAdapter.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER_FWD
#define SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::swing::colorchooser { class DefaultSwatchChooserPanel_RecentSwatchListener; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::swing::colorchooser::DefaultSwatchChooserPanel_RecentSwatchListener>
{
	static constexpr fixed_string class_name = "javax/swing/colorchooser/DefaultSwatchChooserPanel$RecentSwatchListener";
	using base_classes = std::tuple<scapix::java_api::java::awt::event::MouseAdapter, scapix::java_api::java::io::Serializable>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER)
#define SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/java/awt/event/MouseEvent.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class javax::swing::colorchooser::DefaultSwatchChooserPanel_RecentSwatchListener : public jni::object_base<"javax/swing/colorchooser/DefaultSwatchChooserPanel$RecentSwatchListener",
	java::awt::event::MouseAdapter,
	java::io::Serializable>
{
public:

	void mousePressed(jni::ref<java::awt::event::MouseEvent> p1) { return call_method<"mousePressed", void>(p1); }

protected:

	DefaultSwatchChooserPanel_RecentSwatchListener(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_SWING_COLORCHOOSER_DEFAULTSWATCHCHOOSERPANEL_RECENTSWATCHLISTENER
