// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK_FWD
#define SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace android::view {

class ActionMode_Callback;

} // namespace android::view
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::android::view::ActionMode_Callback>
{
	static constexpr fixed_string class_name = "android/view/ActionMode$Callback";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK
#define SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/android/view/ActionMode.h>
#include <scapix/java_api/android/view/Menu.h>
#include <scapix/java_api/android/view/MenuItem.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class android::view::ActionMode_Callback : public jni::object_base<"android/view/ActionMode$Callback",
	java::lang::Object>
{
public:

	jboolean onActionItemClicked(jni::ref<android::view::ActionMode> p1, jni::ref<android::view::MenuItem> p2) { return call_method<"onActionItemClicked", jboolean>(p1, p2); }
	jboolean onCreateActionMode(jni::ref<android::view::ActionMode> p1, jni::ref<android::view::Menu> p2) { return call_method<"onCreateActionMode", jboolean>(p1, p2); }
	void onDestroyActionMode(jni::ref<android::view::ActionMode> p1) { return call_method<"onDestroyActionMode", void>(p1); }
	jboolean onPrepareActionMode(jni::ref<android::view::ActionMode> p1, jni::ref<android::view::Menu> p2) { return call_method<"onPrepareActionMode", jboolean>(p1, p2); }
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ANDROID_VIEW_ACTIONMODE_CALLBACK
#endif // SCAPIX_JAVA_API_FWD
