// Generated by Scapix Java API 2.3
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/jdk/nashorn/api/tree/StatementTree.h>

#ifndef SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE_FWD
#define SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {
namespace jdk::nashorn::api::tree {

class DebuggerTree;

} // namespace jdk::nashorn::api::tree
} // namespace scapix::java_api

template<>
struct scapix::jni::object_traits<scapix::java_api::jdk::nashorn::api::tree::DebuggerTree>
{
	static constexpr fixed_string class_name = "jdk/nashorn/api/tree/DebuggerTree";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::jdk::nashorn::api::tree::StatementTree>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE_FWD

#ifndef SCAPIX_JAVA_API_FWD
#ifndef SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE
#define SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class jdk::nashorn::api::tree::DebuggerTree : public jni::object_base<"jdk/nashorn/api/tree/DebuggerTree",
	java::lang::Object,
	jdk::nashorn::api::tree::StatementTree>
{
public:
};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JDK_NASHORN_API_TREE_DEBUGGERTREE
#endif // SCAPIX_JAVA_API_FWD
