// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/javax/microedition/khronos/egl/EGL10.h>

#ifndef SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11_FWD
#define SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::javax::microedition::khronos::egl { class EGL11; }

template<>
struct scapix::jni::object_traits<scapix::java_api::javax::microedition::khronos::egl::EGL11>
{
	static constexpr fixed_string class_name = "javax/microedition/khronos/egl/EGL11";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::javax::microedition::khronos::egl::EGL10>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11)
#define SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class javax::microedition::khronos::egl::EGL11 : public jni::object_base<"javax/microedition/khronos/egl/EGL11",
	java::lang::Object,
	javax::microedition::khronos::egl::EGL10>
{
public:

	static jint EGL_CONTEXT_LOST() { return get_static_field<"EGL_CONTEXT_LOST", jint>(); }


protected:

	EGL11(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVAX_MICROEDITION_KHRONOS_EGL_EGL11
