// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/awt/peer/ComponentPeer.h>

#ifndef SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER_FWD
#define SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::java::awt::peer { class ScrollbarPeer; }

template<>
struct scapix::jni::object_traits<scapix::java_api::java::awt::peer::ScrollbarPeer>
{
	static constexpr fixed_string class_name = "java/awt/peer/ScrollbarPeer";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::java::awt::peer::ComponentPeer>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER)
#define SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class java::awt::peer::ScrollbarPeer : public jni::object_base<"java/awt/peer/ScrollbarPeer",
	java::lang::Object,
	java::awt::peer::ComponentPeer>
{
public:

	void setValues(jint p1, jint p2, jint p3, jint p4) { return call_method<"setValues", void>(p1, p2, p3, p4); }
	void setLineIncrement(jint p1) { return call_method<"setLineIncrement", void>(p1); }
	void setPageIncrement(jint p1) { return call_method<"setPageIncrement", void>(p1); }

protected:

	ScrollbarPeer(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_JAVA_AWT_PEER_SCROLLBARPEER
