// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/org/omg/CORBA/ExceptionList.h>

#ifndef SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL_FWD
#define SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::com::sun::corba::se::impl::corba { class ExceptionListImpl; }

template<>
struct scapix::jni::object_traits<scapix::java_api::com::sun::corba::se::impl::corba::ExceptionListImpl>
{
	static constexpr fixed_string class_name = "com/sun/corba/se/impl/corba/ExceptionListImpl";
	using base_classes = std::tuple<scapix::java_api::org::omg::CORBA::ExceptionList>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL)
#define SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL

#define SCAPIX_JAVA_API_FWD
#include <scapix/java_api/org/omg/CORBA/TypeCode.h>
#undef SCAPIX_JAVA_API_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class com::sun::corba::se::impl::corba::ExceptionListImpl : public jni::object_base<"com/sun/corba/se/impl/corba/ExceptionListImpl",
	org::omg::CORBA::ExceptionList>
{
public:

	static jni::ref<com::sun::corba::se::impl::corba::ExceptionListImpl> new_object() { return base_::new_object(); }
	jint count() { return call_method<"count", jint>(); }
	void add(jni::ref<org::omg::CORBA::TypeCode> p1) { return call_method<"add", void>(p1); }
	jni::ref<org::omg::CORBA::TypeCode> item(jint p1) { return call_method<"item", jni::ref<org::omg::CORBA::TypeCode>>(p1); }
	void remove(jint p1) { return call_method<"remove", void>(p1); }

protected:

	ExceptionListImpl(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_COM_SUN_CORBA_SE_IMPL_CORBA_EXCEPTIONLISTIMPL
