// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/org/omg/CORBA/portable/IDLEntity.h>

#ifndef SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE_FWD
#define SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::org::omg::PortableServer { class ThreadPolicyValue; }

template<>
struct scapix::jni::object_traits<scapix::java_api::org::omg::PortableServer::ThreadPolicyValue>
{
	static constexpr fixed_string class_name = "org/omg/PortableServer/ThreadPolicyValue";
	using base_classes = std::tuple<scapix::java_api::java::lang::Object, scapix::java_api::org::omg::CORBA::portable::IDLEntity>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE)
#define SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class org::omg::PortableServer::ThreadPolicyValue : public jni::object_base<"org/omg/PortableServer/ThreadPolicyValue",
	java::lang::Object,
	org::omg::CORBA::portable::IDLEntity>
{
public:

	static jint _ORB_CTRL_MODEL() { return get_static_field<"_ORB_CTRL_MODEL", jint>(); }
	static jni::ref<org::omg::PortableServer::ThreadPolicyValue> ORB_CTRL_MODEL() { return get_static_field<"ORB_CTRL_MODEL", jni::ref<org::omg::PortableServer::ThreadPolicyValue>>(); }
	static jint _SINGLE_THREAD_MODEL() { return get_static_field<"_SINGLE_THREAD_MODEL", jint>(); }
	static jni::ref<org::omg::PortableServer::ThreadPolicyValue> SINGLE_THREAD_MODEL() { return get_static_field<"SINGLE_THREAD_MODEL", jni::ref<org::omg::PortableServer::ThreadPolicyValue>>(); }

	jint value() { return call_method<"value", jint>(); }
	static jni::ref<org::omg::PortableServer::ThreadPolicyValue> from_int(jint p1) { return call_static_method<"from_int", jni::ref<org::omg::PortableServer::ThreadPolicyValue>>(p1); }

protected:

	ThreadPolicyValue(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_ORG_OMG_PORTABLESERVER_THREADPOLICYVALUE
