// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/sun/font/CMap.h>

#ifndef SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6_FWD
#define SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::font { class CMap_CMapFormat6; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::font::CMap_CMapFormat6>
{
	static constexpr fixed_string class_name = "sun/font/CMap$CMapFormat6";
	using base_classes = std::tuple<scapix::java_api::sun::font::CMap>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6)
#define SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

// private
class sun::font::CMap_CMapFormat6 : public jni::object_base<"sun/font/CMap$CMapFormat6",
	sun::font::CMap>
{
public:


protected:

	CMap_CMapFormat6(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_FONT_CMAP_CMAPFORMAT6
