// Generated by Scapix Java API 2.0
// https://www.scapix.com

#include <scapix/java_api/sun/font/PhysicalFont.h>

#ifndef SCAPIX_JAVA_API_SUN_FONT_FILEFONT_FWD
#define SCAPIX_JAVA_API_SUN_FONT_FILEFONT_FWD

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api::sun::font { class FileFont; }

template<>
struct scapix::jni::object_traits<scapix::java_api::sun::font::FileFont>
{
	static constexpr fixed_string class_name = "sun/font/FileFont";
	using base_classes = std::tuple<scapix::java_api::sun::font::PhysicalFont>;
};

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_FONT_FILEFONT_FWD

#if !defined(SCAPIX_JAVA_API_FWD) && !defined(SCAPIX_JAVA_API_SUN_FONT_FILEFONT)
#define SCAPIX_JAVA_API_SUN_FONT_FILEFONT

#include <scapix/jni/java_api/macros_push.h>

namespace scapix::java_api {

class sun::font::FileFont : public jni::object_base<"sun/font/FileFont",
	sun::font::PhysicalFont>
{
public:

	jboolean canDoStyle(jint p1) { return call_method<"canDoStyle", jboolean>(p1); }

protected:

	FileFont(handle_type h) : base_(h) {}

};

} // namespace scapix::java_api

#include <scapix/jni/java_api/macros_pop.h>

#endif // SCAPIX_JAVA_API_SUN_FONT_FILEFONT
